namespace core
import core.runtime

/// Base class for an abort
public virtual abstract immutable class Abort extends Error
{
    private let _token : immutable object

    protected constructor(token: immutable object)
    {
        _token = token
    }

    public func reset(token: immutable object)
    {
        if _token == token then
        {
            reset(this)
        }
    }

    @ExternImport("stark_reset_abort")
    private extern static func reset(abortInstance: Abort)
}
