namespace core
import core.runtime

public interface IArray<T> extends ISizeable, MutableIterable<T, int>
{
    /// ref indexer #2, not readable
    func operator [index: int] -> ref T 
        requires index >= 0 && index < size
    { 
        get 
    }

    // // in indexer #3, readable
    // func operator [index: int] -> in T
    //     requires index >= 0 && index < size
    // {            
    //     readable get 
    // }
}
