namespace core
{
    public immutable struct Index 
    {
        public constructor(value: int) {
            this.value = value
        }

        public let value : int

        public static func operator implicit as(value: i32) -> Index => new Index(value)

        public static func operator implicit as(value: int) -> Index => new Index(value)

        public static func operator as(index: Index) -> int => index.value
    }
}