namespace core
{
    public immutable struct Rune
    {
#pragma warning disable CS0169
        private var _value : i32
#pragma warning restore
    }

    public module string_rune_playground
    {
        /// Strings are stored as UTF8 sequences in the library/assembly
        public static const my_str : string = "C'est une chaîne de caractères"

        /// A rune is a i32 Unicode codepoint
        public static const check_rune_constant : rune = 'ê'        
    } 
}