import core.runtime

namespace core
{    
    public partial module diagnostics
    {
        @AttributeUsage(AttributeTargets.MODULE | AttributeTargets.FUNC, multiple: true)
        public class ConditionalAttribute extends Attribute
        {
            public constructor(condition: string)
            {
                this.condition = condition
            }

            public func condition -> string { get }
        }
    }
}