// Copyright (c) Microsoft.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.

using System;
using System.Diagnostics;
using System.Text;
using StarkPlatform.CodeAnalysis.Stark.Symbols;
using StarkPlatform.CodeAnalysis.Stark.Syntax;
using StarkPlatform.CodeAnalysis.Text;

namespace StarkPlatform.CodeAnalysis.Stark
{
    [Flags]
    internal enum UnaryOperatorKind
    {
        // NOTE: these types should line up with the elements in BinaryOperatorKind

        TypeMask = 0x000000FF,

        Int = 0x0000000F,
        UInt = 0x00000010,
        Int8 = 0x00000011,
        UInt8 = 0x00000012,
        Int16 = 0x00000013,
        UShort = 0x00000014,
        Int32 = 0x00000015,
        UInt32 = 0x00000016,
        Int64 = 0x00000017,
        UInt64 = 0x00000018,
        Char = 0x00000019,
        Float32 = 0x0000001A,
        Float64 = 0x0000001B,
        Decimal = 0x0000001C,
        Bool = 0x0000001D,
        _Object = 0x0000001E, // reserved for binary op
        _String = 0x0000001F, // reserved for binary op
        _StringAndObject = 0x00000021, // reserved for binary op
        _ObjectAndString = 0x00000022, // reserved for binary op

        Enum = 0x00000023,
        _EnumAndUnderlying = 0x00000024, // reserved for binary op
        _UnderlyingAndEnum = 0x00000025, // reserved for binary op
        _Delegate = 0x00000026, // reserved for binary op
        Pointer = 0x00000027,
        _PointerAndInt32 = 0x00000028, // reserved for binary op
        _PointerAndUInt32 = 0x00000029, // reserved for binary op
        _PointerAndInt64 = 0x0000002A, // reserved for binary op
        _PointerAndUInt64 = 0x0000002B, // reserved for binary op
        _Int32AndPointer = 0x0000002C, // reserved for binary op
        _UInt32AndPointer = 0x0000002D, // reserved for binary op
        _Int64AndPointer = 0x0000002E, // reserved for binary op
        _UInt64AndPointer = 0x0000002F, // reserved for binary op
        _NullableNull = 0x00000030, // reserved for binary op
        UserDefined = 0x00000031,
        Dynamic = 0x00000032,
        _PointerAndInt = 0x00000033, // reserved for binary op
        _PointerAndUInt = 0x00000034, // reserved for binary op
        _IntAndPointer = 0x00000035, // reserved for binary op
        _UIntAndPointer = 0x00000036, // reserved for binary op

        OpMask = 0x0000FF00,
        PostfixIncrement = 0x00001000,
        PostfixDecrement = 0x00001100,
        PrefixIncrement = 0x00001200,
        PrefixDecrement = 0x00001300,
        UnaryPlus = 0x00001400,
        UnaryMinus = 0x00001500,
        LogicalNegation = 0x00001600,
        BitwiseComplement = 0x00001700,
        True = 0x00001800,
        False = 0x00001900,

        Lifted = 0x00010000,
        _Logical = 0x00020000, // reserved for binary op              
        Checked = 0x00040000,

        Error = 0x00000000,

        Int8PostfixIncrement = Int8 | PostfixIncrement,
        UInt8PostfixIncrement = UInt8 | PostfixIncrement,
        Int16PostfixIncrement = Int16 | PostfixIncrement,
        UInt16PostfixIncrement = UShort | PostfixIncrement,
        Int32PostfixIncrement = Int32 | PostfixIncrement,
        UInt32PostfixIncrement = UInt32 | PostfixIncrement,
        Int64PostfixIncrement = Int64 | PostfixIncrement,
        UInt64PostfixIncrement = UInt64 | PostfixIncrement,
        CharPostfixIncrement = Char | PostfixIncrement,
        Float32PostfixIncrement = Float32 | PostfixIncrement,
        Float64PostfixIncrement = Float64 | PostfixIncrement,
        DecimalPostfixIncrement = Decimal | PostfixIncrement,
        IntPostfixIncrement = Int | PostfixIncrement,
        UIntPostfixIncrement = UInt | PostfixIncrement,

        EnumPostfixIncrement = Enum | PostfixIncrement,
        UserDefinedPostfixIncrement = UserDefined | PostfixIncrement,
        LiftedInt8PostfixIncrement = Lifted | Int8 | PostfixIncrement,
        LiftedUInt8PostfixIncrement = Lifted | UInt8 | PostfixIncrement,
        LiftedInt16PostfixIncrement = Lifted | Int16 | PostfixIncrement,
        LiftedUInt16PostfixIncrement = Lifted | UShort | PostfixIncrement,
        LiftedInt32PostfixIncrement = Lifted | Int32 | PostfixIncrement,
        LiftedUInt32PostfixIncrement = Lifted | UInt32 | PostfixIncrement,
        LiftedInt64PostfixIncrement = Lifted | Int64 | PostfixIncrement,
        LiftedUInt64PostfixIncrement = Lifted | UInt64 | PostfixIncrement,
        LiftedCharPostfixIncrement = Lifted | Char | PostfixIncrement,
        LiftedFloat32PostfixIncrement = Lifted | Float32 | PostfixIncrement,
        LiftedFloat64PostfixIncrement = Lifted | Float64 | PostfixIncrement,
        LiftedDecimalPostfixIncrement = Lifted | Decimal | PostfixIncrement,
        LiftedIntPostfixIncrement = Lifted | Int | PostfixIncrement,
        LiftedUIntPostfixIncrement = Lifted | UInt | PostfixIncrement,

        LiftedEnumPostfixIncrement = Lifted | Enum | PostfixIncrement,
        LiftedUserDefinedPostfixIncrement = Lifted | UserDefined | PostfixIncrement,
        PointerPostfixIncrement = Pointer | PostfixIncrement,
        DynamicPostfixIncrement = Dynamic | PostfixIncrement,

        Int8PrefixIncrement = Int8 | PrefixIncrement,
        UInt8PrefixIncrement = UInt8 | PrefixIncrement,
        Int16PrefixIncrement = Int16 | PrefixIncrement,
        UInt16PrefixIncrement = UShort | PrefixIncrement,
        Int32PrefixIncrement = Int32 | PrefixIncrement,
        UInt32PrefixIncrement = UInt32 | PrefixIncrement,
        Int64PrefixIncrement = Int64 | PrefixIncrement,
        UInt64PrefixIncrement = UInt64 | PrefixIncrement,
        CharPrefixIncrement = Char | PrefixIncrement,
        Float32PrefixIncrement = Float32 | PrefixIncrement,
        Float64PrefixIncrement = Float64 | PrefixIncrement,
        DecimalPrefixIncrement = Decimal | PrefixIncrement,
        IntPrefixIncrement = Int | PrefixIncrement,
        UIntPrefixIncrement = UInt | PrefixIncrement,

        EnumPrefixIncrement = Enum | PrefixIncrement,
        UserDefinedPrefixIncrement = UserDefined | PrefixIncrement,
        LiftedInt8PrefixIncrement = Lifted | Int8 | PrefixIncrement,
        LiftedUInt8PrefixIncrement = Lifted | UInt8 | PrefixIncrement,
        LiftedInt16PrefixIncrement = Lifted | Int16 | PrefixIncrement,
        LiftedUInt16PrefixIncrement = Lifted | UShort | PrefixIncrement,
        LiftedInt32PrefixIncrement = Lifted | Int32 | PrefixIncrement,
        LiftedUInt32PrefixIncrement = Lifted | UInt32 | PrefixIncrement,
        LiftedInt64PrefixIncrement = Lifted | Int64 | PrefixIncrement,
        LiftedUInt64PrefixIncrement = Lifted | UInt64 | PrefixIncrement,
        LiftedCharPrefixIncrement = Lifted | Char | PrefixIncrement,
        LiftedFloat32PrefixIncrement = Lifted | Float32 | PrefixIncrement,
        LiftedFloat64PrefixIncrement = Lifted | Float64 | PrefixIncrement,
        LiftedDecimalPrefixIncrement = Lifted | Decimal | PrefixIncrement,
        LiftedIntPrefixIncrement = Lifted | Int | PrefixIncrement,
        LiftedUIntPrefixIncrement = Lifted | UInt | PrefixIncrement,

        LiftedEnumPrefixIncrement = Lifted | Enum | PrefixIncrement,
        LiftedUserDefinedPrefixIncrement = Lifted | UserDefined | PrefixIncrement,
        PointerPrefixIncrement = Pointer | PrefixIncrement,
        DynamicPrefixIncrement = Dynamic | PrefixIncrement,

        Int8PostfixDecrement = Int8 | PostfixDecrement,
        UInt8PostfixDecrement = UInt8 | PostfixDecrement,
        Int16PostfixDecrement = Int16 | PostfixDecrement,
        UInt16PostfixDecrement = UShort | PostfixDecrement,
        Int32PostfixDecrement = Int32 | PostfixDecrement,
        UInt32PostfixDecrement = UInt32 | PostfixDecrement,
        Int64PostfixDecrement = Int64 | PostfixDecrement,
        UInt64PostfixDecrement = UInt64 | PostfixDecrement,
        CharPostfixDecrement = Char | PostfixDecrement,
        Float32PostfixDecrement = Float32 | PostfixDecrement,
        Float64PostfixDecrement = Float64 | PostfixDecrement,
        DecimalPostfixDecrement = Decimal | PostfixDecrement,
        IntPostfixDecrement = Int | PostfixDecrement,
        UIntPostfixDecrement = UInt | PostfixDecrement,

        EnumPostfixDecrement = Enum | PostfixDecrement,
        UserDefinedPostfixDecrement = UserDefined | PostfixDecrement,
        LiftedInt8PostfixDecrement = Lifted | Int8 | PostfixDecrement,
        LiftedUInt8PostfixDecrement = Lifted | UInt8 | PostfixDecrement,
        LiftedInt16PostfixDecrement = Lifted | Int16 | PostfixDecrement,
        LiftedUInt16PostfixDecrement = Lifted | UShort | PostfixDecrement,
        LiftedInt32PostfixDecrement = Lifted | Int32 | PostfixDecrement,
        LiftedUInt32PostfixDecrement = Lifted | UInt32 | PostfixDecrement,
        LiftedInt64PostfixDecrement = Lifted | Int64 | PostfixDecrement,
        LiftedUInt64PostfixDecrement = Lifted | UInt64 | PostfixDecrement,
        LiftedCharPostfixDecrement = Lifted | Char | PostfixDecrement,
        LiftedFloat32PostfixDecrement = Lifted | Float32 | PostfixDecrement,
        LiftedFloat64PostfixDecrement = Lifted | Float64 | PostfixDecrement,
        LiftedDecimalPostfixDecrement = Lifted | Decimal | PostfixDecrement,
        LiftedIntPostfixDecrement = Lifted | Int | PostfixDecrement,
        LiftedUIntPostfixDecrement = Lifted | UInt | PostfixDecrement,

        LiftedEnumPostfixDecrement = Lifted | Enum | PostfixDecrement,
        LiftedUserDefinedPostfixDecrement = Lifted | UserDefined | PostfixDecrement,
        PointerPostfixDecrement = Pointer | PostfixDecrement,
        DynamicPostfixDecrement = Dynamic | PostfixDecrement,

        Int8PrefixDecrement = Int8 | PrefixDecrement,
        UInt8PrefixDecrement = UInt8 | PrefixDecrement,
        Int16PrefixDecrement = Int16 | PrefixDecrement,
        UInt16PrefixDecrement = UShort | PrefixDecrement,
        Int32PrefixDecrement = Int32 | PrefixDecrement,
        UInt32PrefixDecrement = UInt32 | PrefixDecrement,
        Int64PrefixDecrement = Int64 | PrefixDecrement,
        UInt64PrefixDecrement = UInt64 | PrefixDecrement,
        CharPrefixDecrement = Char | PrefixDecrement,
        Float32PrefixDecrement = Float32 | PrefixDecrement,
        Float64PrefixDecrement = Float64 | PrefixDecrement,
        DecimalPrefixDecrement = Decimal | PrefixDecrement,
        IntPrefixDecrement = Int | PrefixDecrement,
        UIntPrefixDecrement = UInt | PrefixDecrement,

        EnumPrefixDecrement = Enum | PrefixDecrement,
        UserDefinedPrefixDecrement = UserDefined | PrefixDecrement,
        LiftedInt8PrefixDecrement = Lifted | Int8 | PrefixDecrement,
        LiftedUInt8PrefixDecrement = Lifted | UInt8 | PrefixDecrement,
        LiftedInt16PrefixDecrement = Lifted | Int16 | PrefixDecrement,
        LiftedUInt16PrefixDecrement = Lifted | UShort | PrefixDecrement,
        LiftedInt32PrefixDecrement = Lifted | Int32 | PrefixDecrement,
        LiftedUInt32PrefixDecrement = Lifted | UInt32 | PrefixDecrement,
        LiftedInt64PrefixDecrement = Lifted | Int64 | PrefixDecrement,
        LiftedUInt64PrefixDecrement = Lifted | UInt64 | PrefixDecrement,
        LiftedCharPrefixDecrement = Lifted | Char | PrefixDecrement,
        LiftedFloat32PrefixDecrement = Lifted | Float32 | PrefixDecrement,
        LiftedFloat64PrefixDecrement = Lifted | Float64 | PrefixDecrement,
        LiftedDecimalPrefixDecrement = Lifted | Decimal | PrefixDecrement,
        LiftedIntPrefixDecrement = Lifted | Int | PrefixDecrement,
        LiftedUIntPrefixDecrement = Lifted | UInt | PrefixDecrement,

        LiftedEnumPrefixDecrement = Lifted | Enum | PrefixDecrement,
        LiftedUserDefinedPrefixDecrement = Lifted | UserDefined | PrefixDecrement,
        PointerPrefixDecrement = Pointer | PrefixDecrement,
        DynamicPrefixDecrement = Dynamic | PrefixDecrement,

        Int32UnaryPlus = Int32 | UnaryPlus,
        UInt32UnaryPlus = UInt32 | UnaryPlus,
        Int64UnaryPlus = Int64 | UnaryPlus,
        UInt64UnaryPlus = UInt64 | UnaryPlus,
        Float32UnaryPlus = Float32 | UnaryPlus,
        Float64UnaryPlus = Float64 | UnaryPlus,
        DecimalUnaryPlus = Decimal | UnaryPlus,
        IntUnaryPlus = Int | UnaryPlus,
        UIntUnaryPlus = UInt | UnaryPlus,

        UserDefinedUnaryPlus = UserDefined | UnaryPlus,
        LiftedInt32UnaryPlus = Lifted | Int32 | UnaryPlus,
        LiftedUInt32UnaryPlus = Lifted | UInt32 | UnaryPlus,
        LiftedInt64UnaryPlus = Lifted | Int64 | UnaryPlus,
        LiftedUInt64UnaryPlus = Lifted | UInt64 | UnaryPlus,
        LiftedFloat32UnaryPlus = Lifted | Float32 | UnaryPlus,
        LiftedFloat64UnaryPlus = Lifted | Float64 | UnaryPlus,
        LiftedDecimalUnaryPlus = Lifted | Decimal | UnaryPlus,
        LiftedIntUnaryPlus = Lifted | Int | UnaryPlus,
        LiftedUIntUnaryPlus = Lifted | UInt | UnaryPlus,

        LiftedUserDefinedUnaryPlus = Lifted | UserDefined | UnaryPlus,
        DynamicUnaryPlus = Dynamic | UnaryPlus,

        Int32UnaryMinus = Int32 | UnaryMinus,
        Int64UnaryMinus = Int64 | UnaryMinus,
        Float32UnaryMinus = Float32 | UnaryMinus,
        Float64UnaryMinus = Float64 | UnaryMinus,
        DecimalUnaryMinus = Decimal | UnaryMinus,
        IntUnaryMinus = Int | UnaryMinus,

        UserDefinedUnaryMinus = UserDefined | UnaryMinus,
        LiftedInt32UnaryMinus = Lifted | Int32 | UnaryMinus,
        LiftedInt64UnaryMinus = Lifted | Int64 | UnaryMinus,
        LiftedFloat32UnaryMinus = Lifted | Float32 | UnaryMinus,
        LiftedFloat64UnaryMinus = Lifted | Float64 | UnaryMinus,
        LiftedDecimalUnaryMinus = Lifted | Decimal | UnaryMinus,
        LiftedIntUnaryMinus = Lifted | Int | UnaryMinus,

        LiftedUserDefinedUnaryMinus = Lifted | UserDefined | UnaryMinus,
        DynamicUnaryMinus = Dynamic | UnaryMinus,

        BoolLogicalNegation = Bool | LogicalNegation,
        UserDefinedLogicalNegation = UserDefined | LogicalNegation,
        LiftedBoolLogicalNegation = Lifted | Bool | LogicalNegation,
        LiftedUserDefinedLogicalNegation = Lifted | UserDefined | LogicalNegation,
        DynamicLogicalNegation = Dynamic | LogicalNegation,

        Int32BitwiseComplement = Int32 | BitwiseComplement,
        UInt32BitwiseComplement = UInt32 | BitwiseComplement,
        Int64BitwiseComplement = Int64 | BitwiseComplement,
        UInt64BitwiseComplement = UInt64 | BitwiseComplement,
        IntBitwiseComplement = Int | BitwiseComplement,
        UIntBitwiseComplement = UInt | BitwiseComplement,
        EnumBitwiseComplement = Enum | BitwiseComplement,
        UserDefinedBitwiseComplement = UserDefined | BitwiseComplement,
        LiftedInt32BitwiseComplement = Lifted | Int32 | BitwiseComplement,
        LiftedUInt32BitwiseComplement = Lifted | UInt32 | BitwiseComplement,
        LiftedInt64BitwiseComplement = Lifted | Int64 | BitwiseComplement,
        LiftedUInt64BitwiseComplement = Lifted | UInt64 | BitwiseComplement,
        LiftedIntBitwiseComplement = Lifted | Int | BitwiseComplement,
        LiftedUIntBitwiseComplement = Lifted | UInt | BitwiseComplement,
        LiftedEnumBitwiseComplement = Lifted | Enum | BitwiseComplement,
        LiftedUserDefinedBitwiseComplement = Lifted | UserDefined | BitwiseComplement,
        DynamicBitwiseComplement = Dynamic | BitwiseComplement,

        // operator true and operator false are almost always user-defined, and never lifted.
        UserDefinedTrue = UserDefined | True,
        UserDefinedFalse = UserDefined | False,

        // The one time operator true is not user-defined is "if(dyn)" where dyn is of type dynamic.
        // In that case we bind this as a dynamic "operator true" invocation, rather than as a 
        // dynamic conversion to bool.
        DynamicTrue = Dynamic | True,

        // Used during lowering of dynamic logical operators.
        DynamicFalse = Dynamic | False,
    }

    [Flags]
    internal enum BinaryOperatorKind
    {
        // NOTE: these types should line up with the elements in UnaryOperatorKind

        TypeMask = UnaryOperatorKind.TypeMask,

        Int = UnaryOperatorKind.Int,
        UInt = UnaryOperatorKind.UInt,
        Int32 = UnaryOperatorKind.Int32,
        UInt32 = UnaryOperatorKind.UInt32,
        Int64 = UnaryOperatorKind.Int64,
        UInt64 = UnaryOperatorKind.UInt64,
        Char = UnaryOperatorKind.Char, //not used
        Float32 = UnaryOperatorKind.Float32,
        Float64 = UnaryOperatorKind.Float64,
        Decimal = UnaryOperatorKind.Decimal,
        Bool = UnaryOperatorKind.Bool,
        Object = UnaryOperatorKind._Object,
        String = UnaryOperatorKind._String,
        StringAndObject = UnaryOperatorKind._StringAndObject,
        ObjectAndString = UnaryOperatorKind._ObjectAndString,

        Enum = UnaryOperatorKind.Enum,
        EnumAndUnderlying = UnaryOperatorKind._EnumAndUnderlying,
        UnderlyingAndEnum = UnaryOperatorKind._UnderlyingAndEnum,
        Delegate = UnaryOperatorKind._Delegate,
        Pointer = UnaryOperatorKind.Pointer,
        PointerAndInt32 = UnaryOperatorKind._PointerAndInt32,
        PointerAndUInt32 = UnaryOperatorKind._PointerAndUInt32,
        PointerAndInt64 = UnaryOperatorKind._PointerAndInt64,
        PointerAndUInt64 = UnaryOperatorKind._PointerAndUInt64,
        Int32AndPointer = UnaryOperatorKind._Int32AndPointer,
        UInt32AndPointer = UnaryOperatorKind._UInt32AndPointer,
        Int64AndPointer = UnaryOperatorKind._Int64AndPointer,
        UInt64AndPointer = UnaryOperatorKind._UInt64AndPointer,
        NullableNull = UnaryOperatorKind._NullableNull,
        UserDefined = UnaryOperatorKind.UserDefined,
        Dynamic = UnaryOperatorKind.Dynamic,
        PointerAndInt = UnaryOperatorKind._PointerAndInt,
        PointerAndUInt = UnaryOperatorKind._PointerAndUInt,
        IntAndPointer = UnaryOperatorKind._IntAndPointer,
        UIntAndPointer = UnaryOperatorKind._UIntAndPointer,

        OpMask = 0x0000FF00,
        Multiplication = 0x00001000,
        Addition = 0x00001100,
        Subtraction = 0x00001200,
        Division = 0x00001300,
        Remainder = 0x00001400,
        LeftShift = 0x00001500,
        RightShift = 0x00001600,
        Equal = 0x00001700,
        NotEqual = 0x00001800,
        GreaterThan = 0x00001900,
        LessThan = 0x00001A00,
        GreaterThanOrEqual = 0x00001B00,
        LessThanOrEqual = 0x00001C00,
        And = 0x00001D00,
        Xor = 0x00001E00,
        Or = 0x00001F00,

        Lifted = UnaryOperatorKind.Lifted,
        Logical = UnaryOperatorKind._Logical,
        Checked = UnaryOperatorKind.Checked,

        Error = 0x00000000,

        Int32Multiplication = Int32 | Multiplication,
        UInt32Multiplication = UInt32 | Multiplication,
        Int64Multiplication = Int64 | Multiplication,
        UInt64Multiplication = UInt64 | Multiplication,
        Float32Multiplication = Float32 | Multiplication,
        Float64Multiplication = Float64 | Multiplication,
        DecimalMultiplication = Decimal | Multiplication,
        IntMultiplication = Int | Multiplication,
        UIntMultiplication = UInt | Multiplication,

        UserDefinedMultiplication = UserDefined | Multiplication,
        LiftedInt32Multiplication = Lifted | Int32 | Multiplication,
        LiftedUInt32Multiplication = Lifted | UInt32 | Multiplication,
        LiftedInt64Multiplication = Lifted | Int64 | Multiplication,
        LiftedUInt64Multiplication = Lifted | UInt64 | Multiplication,
        LiftedFloat32Multiplication = Lifted | Float32 | Multiplication,
        LiftedFloat64Multiplication = Lifted | Float64 | Multiplication,
        LiftedDecimalMultiplication = Lifted | Decimal | Multiplication,
        LiftedIntMultiplication = Lifted | Int | Multiplication,
        LiftedUIntMultiplication = Lifted | UInt | Multiplication,
        LiftedUserDefinedMultiplication = Lifted | UserDefined | Multiplication,
        DynamicMultiplication = Dynamic | Multiplication,

        Int32Division = Int32 | Division,
        UInt32Division = UInt32 | Division,
        Int64Division = Int64 | Division,
        UInt64Division = UInt64 | Division,
        Float32Division = Float32 | Division,
        Float64Division = Float64 | Division,
        DecimalDivision = Decimal | Division,
        IntDivision = Int | Division,
        UIntDivision = UInt | Division,

        UserDefinedDivision = UserDefined | Division,
        LiftedInt32Division = Lifted | Int32 | Division,
        LiftedUInt32Division = Lifted | UInt32 | Division,
        LiftedInt64Division = Lifted | Int64 | Division,
        LiftedUInt64Division = Lifted | UInt64 | Division,
        LiftedFloat32Division = Lifted | Float32 | Division,
        LiftedFloat64Division = Lifted | Float64 | Division,
        LiftedDecimalDivision = Lifted | Decimal | Division,
        LiftedIntDivision = Lifted | Int | Division,
        LiftedUIntDivision = Lifted | UInt | Division,
        LiftedUserDefinedDivision = Lifted | UserDefined | Division,
        DynamicDivision = Dynamic | Division,

        Int32Remainder = Int32 | Remainder,
        UInt32Remainder = UInt32 | Remainder,
        Int64Remainder = Int64 | Remainder,
        UInt64Remainder = UInt64 | Remainder,
        Float32Remainder = Float32 | Remainder,
        Float64Remainder = Float64 | Remainder,
        DecimalRemainder = Decimal | Remainder,
        IntRemainder = Int | Remainder,
        UIntRemainder = UInt | Remainder,

        UserDefinedRemainder = UserDefined | Remainder,
        LiftedInt32Remainder = Lifted | Int32 | Remainder,
        LiftedUInt32Remainder = Lifted | UInt32 | Remainder,
        LiftedInt64Remainder = Lifted | Int64 | Remainder,
        LiftedUInt64Remainder = Lifted | UInt64 | Remainder,
        LiftedFloat32Remainder = Lifted | Float32 | Remainder,
        LiftedFloat64Remainder = Lifted | Float64 | Remainder,
        LiftedDecimalRemainder = Lifted | Decimal | Remainder,
        LiftedIntRemainder = Lifted | Int | Remainder,
        LiftedUIntRemainder = Lifted | UInt | Remainder,
        LiftedUserDefinedRemainder = Lifted | UserDefined | Remainder,
        DynamicRemainder = Dynamic | Remainder,

        Int32Addition = Int32 | Addition,
        UInt32Addition = UInt32 | Addition,
        Int64Addition = Int64 | Addition,
        UInt64Addition = UInt64 | Addition,
        Float32Addition = Float32 | Addition,
        Float64Addition = Float64 | Addition,
        DecimalAddition = Decimal | Addition,
        IntAddition = Int | Addition,
        UIntAddition = UInt | Addition,

        EnumAndUnderlyingAddition = EnumAndUnderlying | Addition,
        UnderlyingAndEnumAddition = UnderlyingAndEnum | Addition,
        UserDefinedAddition = UserDefined | Addition,
        LiftedInt32Addition = Lifted | Int32 | Addition,
        LiftedUInt32Addition = Lifted | UInt32 | Addition,
        LiftedInt64Addition = Lifted | Int64 | Addition,
        LiftedUInt64Addition = Lifted | UInt64 | Addition,
        LiftedFloat32Addition = Lifted | Float32 | Addition,
        LiftedFloat64Addition = Lifted | Float64 | Addition,
        LiftedDecimalAddition = Lifted | Decimal | Addition,
        LiftedIntAddition = Lifted | Int | Addition,
        LiftedUIntAddition = Lifted | UInt | Addition,

        LiftedEnumAndUnderlyingAddition = Lifted | EnumAndUnderlying | Addition,
        LiftedUnderlyingAndEnumAddition = Lifted | UnderlyingAndEnum | Addition,
        LiftedUserDefinedAddition = Lifted | UserDefined | Addition,
        PointerAndInt32Addition = PointerAndInt32 | Addition,
        PointerAndUInt32Addition = PointerAndUInt32 | Addition,
        PointerAndInt64Addition = PointerAndInt64 | Addition,
        PointerAndUInt64Addition = PointerAndUInt64 | Addition,
        PointerAndIntAddition = PointerAndInt | Addition,
        PointerAndUIntAddition = PointerAndUInt | Addition,
        Int32AndPointerAddition = Int32AndPointer | Addition,
        UInt32AndPointerAddition = UInt32AndPointer | Addition,
        Int64AndPointerAddition = Int64AndPointer | Addition,
        UInt64AndPointerAddition = UInt64AndPointer | Addition,
        IntAndPointerAddition = IntAndPointer | Addition,
        UIntAndPointerAddition = UIntAndPointer | Addition,
        StringConcatenation = String | Addition,
        StringAndObjectConcatenation = StringAndObject | Addition,
        ObjectAndStringConcatenation = ObjectAndString | Addition,
        DelegateCombination = Delegate | Addition,
        DynamicAddition = Dynamic | Addition,

        Int32Subtraction = Int32 | Subtraction,
        UInt32Subtraction = UInt32 | Subtraction,
        Int64Subtraction = Int64 | Subtraction,
        UInt64Subtraction = UInt64 | Subtraction,
        Float32Subtraction = Float32 | Subtraction,
        Float64Subtraction = Float64 | Subtraction,
        DecimalSubtraction = Decimal | Subtraction,
        IntSubtraction = Int | Subtraction,
        UIntSubtraction = UInt | Subtraction,
        EnumSubtraction = Enum | Subtraction,
        EnumAndUnderlyingSubtraction = EnumAndUnderlying | Subtraction,
        UnderlyingAndEnumSubtraction = UnderlyingAndEnum | Subtraction,
        UserDefinedSubtraction = UserDefined | Subtraction,
        Lifted32IntSubtraction = Lifted | Int32 | Subtraction,
        LiftedUInt32Subtraction = Lifted | UInt32 | Subtraction,
        LiftedInt64Subtraction = Lifted | Int64 | Subtraction,
        LiftedUInt64Subtraction = Lifted | UInt64 | Subtraction,
        LiftedFloat32Subtraction = Lifted | Float32 | Subtraction,
        LiftedFloat64Subtraction = Lifted | Float64 | Subtraction,
        LiftedDecimalSubtraction = Lifted | Decimal | Subtraction,
        LiftedIntSubtraction = Lifted | Int | Subtraction,
        LiftedUIntSubtraction = Lifted | UInt | Subtraction,
        LiftedEnumSubtraction = Lifted | Enum | Subtraction,
        LiftedEnumAndUnderlyingSubtraction = Lifted | EnumAndUnderlying | Subtraction,
        LiftedUnderlyingAndEnumSubtraction = Lifted | UnderlyingAndEnum | Subtraction,
        LiftedUserDefinedSubtraction = Lifted | UserDefined | Subtraction,
        DelegateRemoval = Delegate | Subtraction,
        PointerAndInt32Subtraction = PointerAndInt32 | Subtraction,
        PointerAndUInt32Subtraction = PointerAndUInt32 | Subtraction,
        PointerAndInt64Subtraction = PointerAndInt64 | Subtraction,
        PointerAndUInt64Subtraction = PointerAndUInt64 | Subtraction,
        PointerAndIntSubtraction = PointerAndInt | Subtraction,
        PointerAndUIntSubtraction = PointerAndUInt | Subtraction,
        PointerSubtraction = Pointer | Subtraction,
        DynamicSubtraction = Dynamic | Subtraction,

        Int32LeftShift = Int32 | LeftShift,
        UInt32LeftShift = UInt32 | LeftShift,
        Int64LeftShift = Int64 | LeftShift,
        UInt64LeftShift = UInt64 | LeftShift,
        IntLeftShift = Int | LeftShift,
        UIntLeftShift = UInt | LeftShift,
        UserDefinedLeftShift = UserDefined | LeftShift,
        LiftedInt32LeftShift = Lifted | Int32 | LeftShift,
        LiftedUInt32LeftShift = Lifted | UInt32 | LeftShift,
        LiftedInt64LeftShift = Lifted | Int64 | LeftShift,
        LiftedUInt64LeftShift = Lifted | UInt64 | LeftShift,
        LiftedIntLeftShift = Lifted | Int | LeftShift,
        LiftedUIntLeftShift = Lifted | UInt | LeftShift,
        LiftedUserDefinedLeftShift = Lifted | UserDefined | LeftShift,
        DynamicLeftShift = Dynamic | LeftShift,

        Int32RightShift = Int32 | RightShift,
        UInt32RightShift = UInt32 | RightShift,
        Int64RightShift = Int64 | RightShift,
        UInt64RightShift = UInt64 | RightShift,
        IntRightShift = Int | RightShift,
        UIntRightShift = UInt | RightShift,
        UserDefinedRightShift = UserDefined | RightShift,
        LiftedInt32RightShift = Lifted | Int32 | RightShift,
        LiftedUInt32RightShift = Lifted | UInt32 | RightShift,
        LiftedInt64RightShift = Lifted | Int64 | RightShift,
        LiftedUInt64RightShift = Lifted | UInt64 | RightShift,
        LiftedIntRightShift = Lifted | Int | RightShift,
        LiftedUIntRightShift = Lifted | UInt | RightShift,
        LiftedUserDefinedRightShift = Lifted | UserDefined | RightShift,
        DynamicRightShift = Dynamic | RightShift,

        Int32Equal = Int32 | Equal,
        UInt32Equal = UInt32 | Equal,
        Int64Equal = Int64 | Equal,
        UInt64Equal = UInt64 | Equal,
        Float32Equal = Float32 | Equal,
        Float64Equal = Float64 | Equal,
        DecimalEqual = Decimal | Equal,
        IntEqual = Int | Equal,
        UIntEqual = UInt | Equal,
        BoolEqual = Bool | Equal,
        EnumEqual = Enum | Equal,
        NullableNullEqual = NullableNull | Equal,
        UserDefinedEqual = UserDefined | Equal,
        LiftedInt32Equal = Lifted | Int32 | Equal,
        LiftedUInt32Equal = Lifted | UInt32 | Equal,
        LiftedInt64Equal = Lifted | Int64 | Equal,
        LiftedUInt64Equal = Lifted | UInt64 | Equal,
        LiftedFloat32Equal = Lifted | Float32 | Equal,
        LiftedFloat64Equal = Lifted | Float64 | Equal,
        LiftedDecimalEqual = Lifted | Decimal | Equal,
        LiftedIntEqual = Lifted | Int | Equal,
        LiftedUIntEqual = Lifted | UInt | Equal,
        LiftedBoolEqual = Lifted | Bool | Equal,
        LiftedEnumEqual = Lifted | Enum | Equal,
        LiftedUserDefinedEqual = Lifted | UserDefined | Equal,
        ObjectEqual = Object | Equal,
        StringEqual = String | Equal,
        DelegateEqual = Delegate | Equal,
        PointerEqual = Pointer | Equal,
        DynamicEqual = Dynamic | Equal,

        Int32NotEqual = Int32 | NotEqual,
        UInt32NotEqual = UInt32 | NotEqual,
        Int64NotEqual = Int64 | NotEqual,
        UInt64NotEqual = UInt64 | NotEqual,
        Float32NotEqual = Float32 | NotEqual,
        Float64NotEqual = Float64 | NotEqual,
        DecimalNotEqual = Decimal | NotEqual,
        IntNotEqual = Int | NotEqual,
        UIntNotEqual = UInt | NotEqual,
        BoolNotEqual = Bool | NotEqual,
        EnumNotEqual = Enum | NotEqual,
        NullableNullNotEqual = NullableNull | NotEqual,
        UserDefinedNotEqual = UserDefined | NotEqual,
        LiftedInt32NotEqual = Lifted | Int32 | NotEqual,
        LiftedUInt32NotEqual = Lifted | UInt32 | NotEqual,
        LiftedInt64NotEqual = Lifted | Int64 | NotEqual,
        LiftedUInt64NotEqual = Lifted | UInt64 | NotEqual,
        LiftedFloat32NotEqual = Lifted | Float32 | NotEqual,
        LiftedFloat64NotEqual = Lifted | Float64 | NotEqual,
        LiftedDecimalNotEqual = Lifted | Decimal | NotEqual,
        LiftedIntNotEqual = Lifted | Int | NotEqual,
        LiftedUIntNotEqual = Lifted | UInt | NotEqual,
        LiftedBoolNotEqual = Lifted | Bool | NotEqual,
        LiftedEnumNotEqual = Lifted | Enum | NotEqual,
        LiftedUserDefinedNotEqual = Lifted | UserDefined | NotEqual,
        ObjectNotEqual = Object | NotEqual,
        StringNotEqual = String | NotEqual,
        DelegateNotEqual = Delegate | NotEqual,
        PointerNotEqual = Pointer | NotEqual,
        DynamicNotEqual = Dynamic | NotEqual,

        Int32LessThan = Int32 | LessThan,
        UInt32LessThan = UInt32 | LessThan,
        Int64LessThan = Int64 | LessThan,
        UInt64LessThan = UInt64 | LessThan,
        Float32LessThan = Float32 | LessThan,
        Float64LessThan = Float64 | LessThan,
        DecimalLessThan = Decimal | LessThan,
        IntLessThan = Int | LessThan,
        UIntLessThan = UInt | LessThan,
        EnumLessThan = Enum | LessThan,
        UserDefinedLessThan = UserDefined | LessThan,
        LiftedInt32LessThan = Lifted | Int32 | LessThan,
        LiftedUInt32LessThan = Lifted | UInt32 | LessThan,
        LiftedInt64LessThan = Lifted | Int64 | LessThan,
        LiftedUInt64LessThan = Lifted | UInt64 | LessThan,
        LiftedFloat32LessThan = Lifted | Float32 | LessThan,
        LiftedFloat64LessThan = Lifted | Float64 | LessThan,
        LiftedDecimalLessThan = Lifted | Decimal | LessThan,
        LiftedIntLessThan = Lifted | Int | LessThan,
        LiftedUIntLessThan = Lifted | UInt | LessThan,
        LiftedEnumLessThan = Lifted | Enum | LessThan,
        LiftedUserDefinedLessThan = Lifted | UserDefined | LessThan,
        PointerLessThan = Pointer | LessThan,
        DynamicLessThan = Dynamic | LessThan,

        Int32GreaterThan = Int32 | GreaterThan,
        UInt32GreaterThan = UInt32 | GreaterThan,
        Int64GreaterThan = Int64 | GreaterThan,
        UInt64GreaterThan = UInt64 | GreaterThan,
        Float32GreaterThan = Float32 | GreaterThan,
        Float64GreaterThan = Float64 | GreaterThan,
        DecimalGreaterThan = Decimal | GreaterThan,
        IntGreaterThan = Int | GreaterThan,
        UIntGreaterThan = UInt | GreaterThan,
        EnumGreaterThan = Enum | GreaterThan,
        UserDefinedGreaterThan = UserDefined | GreaterThan,
        Lifted32IntGreaterThan = Lifted | Int32 | GreaterThan,
        LiftedUInt32GreaterThan = Lifted | UInt32 | GreaterThan,
        LiftedInt64GreaterThan = Lifted | Int64 | GreaterThan,
        LiftedUInt64GreaterThan = Lifted | UInt64 | GreaterThan,
        LiftedFloat32GreaterThan = Lifted | Float32 | GreaterThan,
        LiftedFloat64GreaterThan = Lifted | Float64 | GreaterThan,
        LiftedDecimalGreaterThan = Lifted | Decimal | GreaterThan,
        LiftedIntGreaterThan = Lifted | Int | GreaterThan,
        LiftedUIntGreaterThan = Lifted | UInt | GreaterThan,
        LiftedEnumGreaterThan = Lifted | Enum | GreaterThan,
        LiftedUserDefinedGreaterThan = Lifted | UserDefined | GreaterThan,
        PointerGreaterThan = Pointer | GreaterThan,
        DynamicGreaterThan = Dynamic | GreaterThan,

        Int32LessThanOrEqual = Int32 | LessThanOrEqual,
        UInt32LessThanOrEqual = UInt32 | LessThanOrEqual,
        Int64LessThanOrEqual = Int64 | LessThanOrEqual,
        UInt64LessThanOrEqual = UInt64 | LessThanOrEqual,
        Float32LessThanOrEqual = Float32 | LessThanOrEqual,
        Float64LessThanOrEqual = Float64 | LessThanOrEqual,
        DecimalLessThanOrEqual = Decimal | LessThanOrEqual,
        IntLessThanOrEqual = Int | LessThanOrEqual,
        UIntLessThanOrEqual = UInt | LessThanOrEqual,
        EnumLessThanOrEqual = Enum | LessThanOrEqual,
        UserDefinedLessThanOrEqual = UserDefined | LessThanOrEqual,
        LiftedInt32LessThanOrEqual = Lifted | Int32 | LessThanOrEqual,
        LiftedUInt32LessThanOrEqual = Lifted | UInt32 | LessThanOrEqual,
        LiftedInt64LessThanOrEqual = Lifted | Int64 | LessThanOrEqual,
        LiftedUInt64LessThanOrEqual = Lifted | UInt64 | LessThanOrEqual,
        LiftedFloat32LessThanOrEqual = Lifted | Float32 | LessThanOrEqual,
        LiftedFloat64LessThanOrEqual = Lifted | Float64 | LessThanOrEqual,
        LiftedDecimalLessThanOrEqual = Lifted | Decimal | LessThanOrEqual,
        LiftedIntLessThanOrEqual = Lifted | Int | LessThanOrEqual,
        LiftedUIntLessThanOrEqual = Lifted | UInt | LessThanOrEqual,
        LiftedEnumLessThanOrEqual = Lifted | Enum | LessThanOrEqual,
        LiftedUserDefinedLessThanOrEqual = Lifted | UserDefined | LessThanOrEqual,
        PointerLessThanOrEqual = Pointer | LessThanOrEqual,
        DynamicLessThanOrEqual = Dynamic | LessThanOrEqual,

        Int32GreaterThanOrEqual = Int32 | GreaterThanOrEqual,
        UInt32GreaterThanOrEqual = UInt32 | GreaterThanOrEqual,
        Int64GreaterThanOrEqual = Int64 | GreaterThanOrEqual,
        UInt64GreaterThanOrEqual = UInt64 | GreaterThanOrEqual,
        Float32GreaterThanOrEqual = Float32 | GreaterThanOrEqual,
        Float64GreaterThanOrEqual = Float64 | GreaterThanOrEqual,
        DecimalGreaterThanOrEqual = Decimal | GreaterThanOrEqual,
        IntGreaterThanOrEqual = Int | GreaterThanOrEqual,
        UIntGreaterThanOrEqual = UInt | GreaterThanOrEqual,
        EnumGreaterThanOrEqual = Enum | GreaterThanOrEqual,
        UserDefinedGreaterThanOrEqual = UserDefined | GreaterThanOrEqual,
        LiftedInt32GreaterThanOrEqual = Lifted | Int32 | GreaterThanOrEqual,
        LiftedUInt32GreaterThanOrEqual = Lifted | UInt32 | GreaterThanOrEqual,
        LiftedInt64GreaterThanOrEqual = Lifted | Int64 | GreaterThanOrEqual,
        LiftedUInt64GreaterThanOrEqual = Lifted | UInt64 | GreaterThanOrEqual,
        LiftedFloat32GreaterThanOrEqual = Lifted | Float32 | GreaterThanOrEqual,
        LiftedFloat64GreaterThanOrEqual = Lifted | Float64 | GreaterThanOrEqual,
        LiftedDecimalGreaterThanOrEqual = Lifted | Decimal | GreaterThanOrEqual,
        LiftedIntGreaterThanOrEqual = Lifted | Int | GreaterThanOrEqual,
        LiftedUIntGreaterThanOrEqual = Lifted | UInt | GreaterThanOrEqual,
        LiftedEnumGreaterThanOrEqual = Lifted | Enum | GreaterThanOrEqual,
        LiftedUserDefinedGreaterThanOrEqual = Lifted | UserDefined | GreaterThanOrEqual,
        PointerGreaterThanOrEqual = Pointer | GreaterThanOrEqual,
        DynamicGreaterThanOrEqual = Dynamic | GreaterThanOrEqual,

        Int32And = Int32 | And,
        UInt32And = UInt32 | And,
        Int64And = Int64 | And,
        UInt64And = UInt64 | And,
        IntAnd = Int | And,
        UIntAnd = UInt | And,
        EnumAnd = Enum | And,
        BoolAnd = Bool | And,
        UserDefinedAnd = UserDefined | And,
        LiftedInt32And = Lifted | Int32 | And,
        LiftedUInt32And = Lifted | UInt32 | And,
        LiftedInt64And = Lifted | Int64 | And,
        LiftedUInt64And = Lifted | UInt64 | And,
        LiftedIntAnd = Lifted | Int | And,
        LiftedUIntAnd = Lifted | UInt | And,
        LiftedEnumAnd = Lifted | Enum | And,
        LiftedBoolAnd = Lifted | Bool | And,
        LiftedUserDefinedAnd = Lifted | UserDefined | And,
        DynamicAnd = Dynamic | And,

        LogicalAnd = And | Logical,
        LogicalBoolAnd = Bool | LogicalAnd,
        LogicalUserDefinedAnd = UserDefined | LogicalAnd,
        DynamicLogicalAnd = Dynamic | LogicalAnd,

        Int32Or = Int32 | Or,
        UInt32Or = UInt32 | Or,
        Int64Or = Int64 | Or,
        UInt64Or = UInt64 | Or,
        IntOr = Int | Or,
        UIntOr = UInt | Or,
        EnumOr = Enum | Or,
        BoolOr = Bool | Or,
        UserDefinedOr = UserDefined | Or,
        LiftedInt32Or = Lifted | Int32 | Or,
        LiftedUInt32Or = Lifted | UInt32 | Or,
        LiftedInt64Or = Lifted | Int64 | Or,
        LiftedUInt64Or = Lifted | UInt64 | Or,
        LiftedIntOr = Lifted | Int | Or,
        LiftedUIntOr = Lifted | UInt | Or,
        LiftedEnumOr = Lifted | Enum | Or,
        LiftedBoolOr = Lifted | Bool | Or,
        LiftedUserDefinedOr = Lifted | UserDefined | Or,
        DynamicOr = Dynamic | Or,

        LogicalOr = Or | Logical,
        LogicalBoolOr = Bool | LogicalOr,
        LogicalUserDefinedOr = UserDefined | LogicalOr,
        DynamicLogicalOr = Dynamic | LogicalOr,

        Int32Xor = Int32 | Xor,
        UInt32Xor = UInt32 | Xor,
        Int64Xor = Int64 | Xor,
        UInt64Xor = UInt64 | Xor,
        IntXor = Int | Xor,
        UIntXor = UInt | Xor,
        EnumXor = Enum | Xor,
        BoolXor = Bool | Xor,
        UserDefinedXor = UserDefined | Xor,
        LiftedInt32Xor = Lifted | Int32 | Xor,
        LiftedUInt32Xor = Lifted | UInt32 | Xor,
        LiftedInt64Xor = Lifted | Int64 | Xor,
        LiftedUInt64Xor = Lifted | UInt64 | Xor,
        LiftedIntXor = Lifted | Int | Xor,
        LiftedUIntXor = Lifted | UInt | Xor,
        LiftedEnumXor = Lifted | Enum | Xor,
        LiftedBoolXor = Lifted | Bool | Xor,
        LiftedUserDefinedXor = Lifted | UserDefined | Xor,
        DynamicXor = Dynamic | Xor,
    }
}
