//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarkPlatform.Reflection.Resources {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal partial class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StarkPlatform.Reflection.Metadata.Resources.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly already added..
        /// </summary>
        internal static string AssemblyAlreadyAdded {
            get {
                return ResourceManager.GetString("AssemblyAlreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base reader must be a full metadata reader..
        /// </summary>
        internal static string BaseReaderMustBeFullMetadataReader {
            get {
                return ResourceManager.GetString("BaseReaderMustBeFullMetadataReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blob is to large..
        /// </summary>
        internal static string BlobTooLarge {
            get {
                return ResourceManager.GetString("BlobTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation is not valid on this builder as it has been linked with another one..
        /// </summary>
        internal static string BuilderAlreadyLinked {
            get {
                return ResourceManager.GetString("BuilderAlreadyLinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Builder must be aligned to 4 byte boundary..
        /// </summary>
        internal static string BuilderMustAligned {
            get {
                return ResourceManager.GetString("BuilderMustAligned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t get a heap offset for a virtual heap handle.
        /// </summary>
        internal static string CantGetOffsetForVirtualHeapHandle {
            get {
                return ResourceManager.GetString("CantGetOffsetForVirtualHeapHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t emit a branch or exception region, the current encoder not created with a control flow builder..
        /// </summary>
        internal static string ControlFlowBuilderNotAvailable {
            get {
                return ResourceManager.GetString("ControlFlowBuilderNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data too big to fit in memory..
        /// </summary>
        internal static string DataTooBig {
            get {
                return ResourceManager.GetString("DataTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The distance between the instruction {0} (offset {1}) and the target label doesn&apos;t fit the operand size: {2}.
        /// </summary>
        internal static string DistanceBetweenInstructionAndLabelTooBig {
            get {
                return ResourceManager.GetString("DistanceBetweenInstructionAndLabelTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnCMap table not sorted or has missing records..
        /// </summary>
        internal static string EnCMapNotSorted {
            get {
                return ResourceManager.GetString("EnCMapNotSorted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected array of size {0}..
        /// </summary>
        internal static string ExpectedArrayOfSize {
            get {
                return ResourceManager.GetString("ExpectedArrayOfSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected list of size {0}..
        /// </summary>
        internal static string ExpectedListOfSize {
            get {
                return ResourceManager.GetString("ExpectedListOfSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected non-empty array..
        /// </summary>
        internal static string ExpectedNonEmptyArray {
            get {
                return ResourceManager.GetString("ExpectedNonEmptyArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected non-empty list..
        /// </summary>
        internal static string ExpectedNonEmptyList {
            get {
                return ResourceManager.GetString("ExpectedNonEmptyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected non-empty string..
        /// </summary>
        internal static string ExpectedNonEmptyString {
            get {
                return ResourceManager.GetString("ExpectedNonEmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handle belongs to a future generation.
        /// </summary>
        internal static string HandleBelongsToFutureGeneration {
            get {
                return ResourceManager.GetString("HandleBelongsToFutureGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hash must be at least {0}B long..
        /// </summary>
        internal static string HashTooShort {
            get {
                return ResourceManager.GetString("HashTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The limit on the size of {0} heap has been exceeded..
        /// </summary>
        internal static string HeapSizeLimitExceeded {
            get {
                return ResourceManager.GetString("HeapSizeLimitExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal tables in compressed metadata stream..
        /// </summary>
        internal static string IllegalTablesInCompressedMetadataStream {
            get {
                return ResourceManager.GetString("IllegalTablesInCompressedMetadataStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image is too small..
        /// </summary>
        internal static string ImageTooSmall {
            get {
                return ResourceManager.GetString("ImageTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image is either too small or contains an invalid byte offset or count..
        /// </summary>
        internal static string ImageTooSmallOrContainsInvalidOffsetOrCount {
            get {
                return ResourceManager.GetString("ImageTooSmallOrContainsInvalidOffsetOrCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid coded index..
        /// </summary>
        internal static string InvalidCodedIndex {
            get {
                return ResourceManager.GetString("InvalidCodedIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid compressed integer..
        /// </summary>
        internal static string InvalidCompressedInteger {
            get {
                return ResourceManager.GetString("InvalidCompressedInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid constant value..
        /// </summary>
        internal static string InvalidConstantValue {
            get {
                return ResourceManager.GetString("InvalidConstantValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of type &apos;{0}&apos; is not a constant..
        /// </summary>
        internal static string InvalidConstantValueOfType {
            get {
                return ResourceManager.GetString("InvalidConstantValueOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid COR header size..
        /// </summary>
        internal static string InvalidCorHeaderSize {
            get {
                return ResourceManager.GetString("InvalidCorHeaderSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of field Characteristics in debug directory entry must be zero..
        /// </summary>
        internal static string InvalidDebugDirectoryEntryCharacteristics {
            get {
                return ResourceManager.GetString("InvalidDebugDirectoryEntryCharacteristics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid directory relative virtual address..
        /// </summary>
        internal static string InvalidDirectoryRVA {
            get {
                return ResourceManager.GetString("InvalidDirectoryRVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid directory size..
        /// </summary>
        internal static string InvalidDirectorySize {
            get {
                return ResourceManager.GetString("InvalidDirectorySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid document name..
        /// </summary>
        internal static string InvalidDocumentName {
            get {
                return ResourceManager.GetString("InvalidDocumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid entry point token: 0x{0:8X}.
        /// </summary>
        internal static string InvalidEntryPointToken {
            get {
                return ResourceManager.GetString("InvalidEntryPointToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid exception region bounds: start offset ({0}) is greater than end offset ({1})..
        /// </summary>
        internal static string InvalidExceptionRegionBounds {
            get {
                return ResourceManager.GetString("InvalidExceptionRegionBounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid handle..
        /// </summary>
        internal static string InvalidHandle {
            get {
                return ResourceManager.GetString("InvalidHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid import definition kind: {0}..
        /// </summary>
        internal static string InvalidImportDefinitionKind {
            get {
                return ResourceManager.GetString("InvalidImportDefinitionKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid local signature token: 0x{0:X8}.
        /// </summary>
        internal static string InvalidLocalSignatureToken {
            get {
                return ResourceManager.GetString("InvalidLocalSignatureToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid metadata section span..
        /// </summary>
        internal static string InvalidMetadataSectionSpan {
            get {
                return ResourceManager.GetString("InvalidMetadataSectionSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Metadata stream format..
        /// </summary>
        internal static string InvalidMetadataStreamFormat {
            get {
                return ResourceManager.GetString("InvalidMetadataStreamFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid method header: 0x{0:X2}.
        /// </summary>
        internal static string InvalidMethodHeader1 {
            get {
                return ResourceManager.GetString("InvalidMethodHeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid method header: 0x{0:X2} 0x{1:X2}.
        /// </summary>
        internal static string InvalidMethodHeader2 {
            get {
                return ResourceManager.GetString("InvalidMethodHeader2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid relative virtual address (RVA): 0x{0:X8}.
        /// </summary>
        internal static string InvalidMethodRva {
            get {
                return ResourceManager.GetString("InvalidMethodRva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number of sections in declared in PE header..
        /// </summary>
        internal static string InvalidNumberOfSections {
            get {
                return ResourceManager.GetString("InvalidNumberOfSections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid PDB Checksum data format..
        /// </summary>
        internal static string InvalidPdbChecksumDataFormat {
            get {
                return ResourceManager.GetString("InvalidPdbChecksumDataFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid PE signature..
        /// </summary>
        internal static string InvalidPESignature {
            get {
                return ResourceManager.GetString("InvalidPESignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid row count: {0}.
        /// </summary>
        internal static string InvalidRowCount {
            get {
                return ResourceManager.GetString("InvalidRowCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid SEH header: 0x{0:X2}.
        /// </summary>
        internal static string InvalidSehHeader {
            get {
                return ResourceManager.GetString("InvalidSehHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid serialized string..
        /// </summary>
        internal static string InvalidSerializedString {
            get {
                return ResourceManager.GetString("InvalidSerializedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid signature..
        /// </summary>
        internal static string InvalidSignature {
            get {
                return ResourceManager.GetString("InvalidSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid token..
        /// </summary>
        internal static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid type size..
        /// </summary>
        internal static string InvalidTypeSize {
            get {
                return ResourceManager.GetString("InvalidTypeSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified label doesn&apos;t belong to the current builder..
        /// </summary>
        internal static string LabelDoesntBelongToBuilder {
            get {
                return ResourceManager.GetString("LabelDoesntBelongToBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label {0} has not been marked..
        /// </summary>
        internal static string LabelNotMarked {
            get {
                return ResourceManager.GetString("LabelNotMarked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata header too small..
        /// </summary>
        internal static string MetadataHeaderTooSmall {
            get {
                return ResourceManager.GetString("MetadataHeaderTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata image doesn&apos;t represent an assembly..
        /// </summary>
        internal static string MetadataImageDoesNotRepresentAnAssembly {
            get {
                return ResourceManager.GetString("MetadataImageDoesNotRepresentAnAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid COR20 header signature..
        /// </summary>
        internal static string MetadataSignature {
            get {
                return ResourceManager.GetString("MetadataSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MetadataStringDecoder instance used to instantiate the Metadata reader must have a UTF8 encoding..
        /// </summary>
        internal static string MetadataStringDecoderEncodingMustBeUtf8 {
            get {
                return ResourceManager.GetString("MetadataStringDecoderEncodingMustBeUtf8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata table header too small..
        /// </summary>
        internal static string MetadataTableHeaderTooSmall {
            get {
                return ResourceManager.GetString("MetadataTableHeaderTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata table {0} not sorted..
        /// </summary>
        internal static string MetadataTableNotSorted {
            get {
                return ResourceManager.GetString("MetadataTableNotSorted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata tables too small..
        /// </summary>
        internal static string MetadataTablesTooSmall {
            get {
                return ResourceManager.GetString("MetadataTablesTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata version too long..
        /// </summary>
        internal static string MetadataVersionTooLong {
            get {
                return ResourceManager.GetString("MetadataVersionTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method body was created with no exception regions..
        /// </summary>
        internal static string MethodHasNoExceptionRegions {
            get {
                return ResourceManager.GetString("MethodHasNoExceptionRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing data directory..
        /// </summary>
        internal static string MissingDataDirectory {
            get {
                return ResourceManager.GetString("MissingDataDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module already added..
        /// </summary>
        internal static string ModuleAlreadyAdded {
            get {
                return ResourceManager.GetString("ModuleAlreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number of rows of Module table: {0}..
        /// </summary>
        internal static string ModuleTableInvalidNumberOfRows {
            get {
                return ResourceManager.GetString("ModuleTableInvalidNumberOfRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must not return null..
        /// </summary>
        internal static string MustNotReturnNull {
            get {
                return ResourceManager.GetString("MustNotReturnNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough space for Blob stream..
        /// </summary>
        internal static string NotEnoughSpaceForBlobStream {
            get {
                return ResourceManager.GetString("NotEnoughSpaceForBlobStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough space for GUID stream..
        /// </summary>
        internal static string NotEnoughSpaceForGUIDStream {
            get {
                return ResourceManager.GetString("NotEnoughSpaceForGUIDStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough space for Metadata stream..
        /// </summary>
        internal static string NotEnoughSpaceForMetadataStream {
            get {
                return ResourceManager.GetString("NotEnoughSpaceForMetadataStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough space for stream header name..
        /// </summary>
        internal static string NotEnoughSpaceForStreamHeaderName {
            get {
                return ResourceManager.GetString("NotEnoughSpaceForStreamHeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough space for String stream..
        /// </summary>
        internal static string NotEnoughSpaceForStringStream {
            get {
                return ResourceManager.GetString("NotEnoughSpaceForStringStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough space for version string..
        /// </summary>
        internal static string NotEnoughSpaceForVersionString {
            get {
                return ResourceManager.GetString("NotEnoughSpaceForVersionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified handle is not a valid metadata heap handle..
        /// </summary>
        internal static string NotMetadataHeapHandle {
            get {
                return ResourceManager.GetString("NotMetadataHeapHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified handle is not a valid metadata table or UserString heap handle..
        /// </summary>
        internal static string NotMetadataTableOrUserStringHandle {
            get {
                return ResourceManager.GetString("NotMetadataTableOrUserStringHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified handle is not a TypeDefinitionHandle or TypeRefererenceHandle..
        /// </summary>
        internal static string NotTypeDefOrRefHandle {
            get {
                return ResourceManager.GetString("NotTypeDefOrRefHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified handle is not a TypeDefinitionHandle, TypeRefererenceHandle, or TypeSpecificationHandle..
        /// </summary>
        internal static string NotTypeDefOrRefOrSpecHandle {
            get {
                return ResourceManager.GetString("NotTypeDefOrRefOrSpecHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read out of bounds..
        /// </summary>
        internal static string OutOfBoundsRead {
            get {
                return ResourceManager.GetString("OutOfBoundsRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write out of bounds..
        /// </summary>
        internal static string OutOfBoundsWrite {
            get {
                return ResourceManager.GetString("OutOfBoundsWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PE image does not have metadata..
        /// </summary>
        internal static string PEImageDoesNotHaveMetadata {
            get {
                return ResourceManager.GetString("PEImageDoesNotHaveMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PE image not available..
        /// </summary>
        internal static string PEImageNotAvailable {
            get {
                return ResourceManager.GetString("PEImageNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified readers must be minimal delta metadata readers..
        /// </summary>
        internal static string ReadersMustBeDeltaReaders {
            get {
                return ResourceManager.GetString("ReadersMustBeDeltaReaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The size of the builder returned by {0}.{1} is smaller than requested..
        /// </summary>
        internal static string ReturnedBuilderSizeTooSmall {
            get {
                return ResourceManager.GetString("ReturnedBuilderSizeTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row count must be zero for table #{0}..
        /// </summary>
        internal static string RowCountMustBeZero {
            get {
                return ResourceManager.GetString("RowCountMustBeZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row count specified for table index {0} is out of allowed range..
        /// </summary>
        internal static string RowCountOutOfRange {
            get {
                return ResourceManager.GetString("RowCountOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row ID or heap offset is too large..
        /// </summary>
        internal static string RowIdOrHeapOffsetTooLarge {
            get {
                return ResourceManager.GetString("RowIdOrHeapOffsetTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section too small..
        /// </summary>
        internal static string SectionTooSmall {
            get {
                return ResourceManager.GetString("SectionTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence point value is out of range..
        /// </summary>
        internal static string SequencePointValueOutOfRange {
            get {
                return ResourceManager.GetString("SequencePointValueOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t add vararg parameters to non-vararg signature..
        /// </summary>
        internal static string SignatureNotVarArg {
            get {
                return ResourceManager.GetString("SignatureNotVarArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature provider returned invalid signature..
        /// </summary>
        internal static string SignatureProviderReturnedInvalidSignature {
            get {
                return ResourceManager.GetString("SignatureProviderReturnedInvalidSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature type sequence must have at least one element..
        /// </summary>
        internal static string SignatureTypeSequenceMustHaveAtLeastOneElement {
            get {
                return ResourceManager.GetString("SignatureTypeSequenceMustHaveAtLeastOneElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declared size doesn&apos;t correspond to the actual size..
        /// </summary>
        internal static string SizeMismatch {
            get {
                return ResourceManager.GetString("SizeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standalone debug metadata image doesn&apos;t contain Module table..
        /// </summary>
        internal static string StandaloneDebugMetadataImageDoesNotContainModuleTable {
            get {
                return ResourceManager.GetString("StandaloneDebugMetadataImageDoesNotContainModuleTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream header too small..
        /// </summary>
        internal static string StreamHeaderTooSmall {
            get {
                return ResourceManager.GetString("StreamHeaderTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream must support read and seek operations..
        /// </summary>
        internal static string StreamMustSupportReadAndSeek {
            get {
                return ResourceManager.GetString("StreamMustSupportReadAndSeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream length minus starting position is too large to hold a PEImage..
        /// </summary>
        internal static string StreamTooLarge {
            get {
                return ResourceManager.GetString("StreamTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table row count space to small..
        /// </summary>
        internal static string TableRowCountSpaceTooSmall {
            get {
                return ResourceManager.GetString("TableRowCountSpaceTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are too many exception regions..
        /// </summary>
        internal static string TooManyExceptionRegions {
            get {
                return ResourceManager.GetString("TooManyExceptionRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are too many subnamespaces..
        /// </summary>
        internal static string TooManySubnamespaces {
            get {
                return ResourceManager.GetString("TooManySubnamespaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected array of length {0}..
        /// </summary>
        internal static string UnexpectedArrayLength {
            get {
                return ResourceManager.GetString("UnexpectedArrayLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected CodeView data signature value..
        /// </summary>
        internal static string UnexpectedCodeViewDataSignature {
            get {
                return ResourceManager.GetString("UnexpectedCodeViewDataSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Debug directory was not of type {0}..
        /// </summary>
        internal static string UnexpectedDebugDirectoryType {
            get {
                return ResourceManager.GetString("UnexpectedDebugDirectoryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected Embedded Portable PDB data signature value..
        /// </summary>
        internal static string UnexpectedEmbeddedPortablePdbDataSignature {
            get {
                return ResourceManager.GetString("UnexpectedEmbeddedPortablePdbDataSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected handle kind: {0}..
        /// </summary>
        internal static string UnexpectedHandleKind {
            get {
                return ResourceManager.GetString("UnexpectedHandleKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected op-code: {0}..
        /// </summary>
        internal static string UnexpectedOpCode {
            get {
                return ResourceManager.GetString("UnexpectedOpCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected signature header for &apos;{0}&apos;, but found &apos;{1}&apos; (0x{2:x2})..
        /// </summary>
        internal static string UnexpectedSignatureHeader {
            get {
                return ResourceManager.GetString("UnexpectedSignatureHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected signature header for &apos;{0}&apos; or &apos;{1}&apos;, but found &apos;{2}&apos; (0x{3:x2})..
        /// </summary>
        internal static string UnexpectedSignatureHeader2 {
            get {
                return ResourceManager.GetString("UnexpectedSignatureHeader2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected SignatureTypeCode: (0x{0:x})..
        /// </summary>
        internal static string UnexpectedSignatureTypeCode {
            get {
                return ResourceManager.GetString("UnexpectedSignatureTypeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected stream end..
        /// </summary>
        internal static string UnexpectedStreamEnd {
            get {
                return ResourceManager.GetString("UnexpectedStreamEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown file format..
        /// </summary>
        internal static string UnknownFileFormat {
            get {
                return ResourceManager.GetString("UnknownFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown PE Magic value..
        /// </summary>
        internal static string UnknownPEMagicValue {
            get {
                return ResourceManager.GetString("UnknownPEMagicValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown section name: &apos;{0}&apos;..
        /// </summary>
        internal static string UnknownSectionName {
            get {
                return ResourceManager.GetString("UnknownSectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown tables: 0x{0:x16}..
        /// </summary>
        internal static string UnknownTables {
            get {
                return ResourceManager.GetString("UnknownTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported format version: {0}.
        /// </summary>
        internal static string UnsupportedFormatVersion {
            get {
                return ResourceManager.GetString("UnsupportedFormatVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be multiple of {0}..
        /// </summary>
        internal static string ValueMustBeMultiple {
            get {
                return ResourceManager.GetString("ValueMustBeMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is too large..
        /// </summary>
        internal static string ValueTooLarge {
            get {
                return ResourceManager.GetString("ValueTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing mscorlib reference in AssemblyRef table..
        /// </summary>
        internal static string WinMDMissingMscorlibRef {
            get {
                return ResourceManager.GetString("WinMDMissingMscorlibRef", resourceCulture);
            }
        }
    }
}
