// Copyright (c) Microsoft.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.

// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("ApiDesign", "RS0026:Do not add multiple public overloads with optional parameters", Justification = "<Pending>", Scope = "member", Target = "~M:StarkPlatform.CodeAnalysis.Stark.CSharpExtensions.GetDeclaredSymbol(StarkPlatform.CodeAnalysis.SemanticModel,StarkPlatform.CodeAnalysis.Stark.Syntax.DeclarationPatternSyntax,System.Threading.CancellationToken)~StarkPlatform.CodeAnalysis.ISymbol")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("ApiDesign", "RS0027:Public API with optional parameter(s) should have the most parameters amongst its public overloads.", Justification = "<Pending>", Scope = "member", Target = "~M:StarkPlatform.CodeAnalysis.Stark.SyntaxFactory.TupleType(StarkPlatform.CodeAnalysis.SeparatedSyntaxList{StarkPlatform.CodeAnalysis.Stark.Syntax.TupleElementSyntax})~StarkPlatform.CodeAnalysis.Stark.Syntax.TupleTypeSyntax")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("ApiDesign", "RS0027:Public API with optional parameter(s) should have the most parameters amongst its public overloads.", Justification = "<Pending>", Scope = "member", Target = "~M:StarkPlatform.CodeAnalysis.Stark.SyntaxFactory.TupleExpression(StarkPlatform.CodeAnalysis.SeparatedSyntaxList{StarkPlatform.CodeAnalysis.Stark.Syntax.ArgumentSyntax})~StarkPlatform.CodeAnalysis.Stark.Syntax.TupleExpressionSyntax")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("ApiDesign", "RS0027:Public API with optional parameter(s) should have the most parameters amongst its public overloads.", Justification = "<Pending>", Scope = "member", Target = "~M:StarkPlatform.CodeAnalysis.Stark.SyntaxFactory.WhenClause(StarkPlatform.CodeAnalysis.Stark.Syntax.ExpressionSyntax)~StarkPlatform.CodeAnalysis.Stark.Syntax.WhenClauseSyntax")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("ApiDesign", "RS0027:Public API with optional parameter(s) should have the most parameters amongst its public overloads.", Justification = "<Pending>", Scope = "member", Target = "~M:StarkPlatform.CodeAnalysis.Stark.SyntaxFactory.IncompleteMember(StarkPlatform.CodeAnalysis.Stark.Syntax.TypeSyntax)~StarkPlatform.CodeAnalysis.Stark.Syntax.IncompleteMemberSyntax")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("ApiDesign", "RS0027:Public API with optional parameter(s) should have the most parameters amongst its public overloads.", Justification = "<Pending>", Scope = "member", Target = "~M:StarkPlatform.CodeAnalysis.Stark.SyntaxFactory.ReturnStatement(StarkPlatform.CodeAnalysis.Stark.Syntax.ExpressionSyntax)~StarkPlatform.CodeAnalysis.Stark.Syntax.ReturnStatementSyntax")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("ApiDesign", "RS0027:Public API with optional parameter(s) should have the most parameters amongst its public overloads.", Justification = "<Pending>", Scope = "member", Target = "~M:StarkPlatform.CodeAnalysis.Stark.SyntaxFactory.DeconstructionVariablesVar(StarkPlatform.CodeAnalysis.Stark.Syntax.TupleExpressionSyntax)~StarkPlatform.CodeAnalysis.Stark.Syntax.DeconstructionVariablesVarSyntax")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("ApiDesign", "RS0027:Public API with optional parameter(s) should have the most parameters amongst its public overloads.", Justification = "<Pending>", Scope = "member", Target = "~M:StarkPlatform.CodeAnalysis.Stark.SyntaxFactory.LocalDeclarationStatement(StarkPlatform.CodeAnalysis.SyntaxTokenList)~StarkPlatform.CodeAnalysis.Stark.Syntax.LocalDeclarationStatementSyntax")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("ApiDesign", "RS0027:Public API with optional parameter(s) should have the most parameters amongst its public overloads.", Justification = "<Pending>", Scope = "member", Target = "~M:StarkPlatform.CodeAnalysis.Stark.SyntaxFactory.VariableDeconstructionDeclarator(StarkPlatform.CodeAnalysis.SeparatedSyntaxList{StarkPlatform.CodeAnalysis.Stark.Syntax.VariableDeclarationSyntax})~StarkPlatform.CodeAnalysis.Stark.Syntax.VariableDeconstructionDeclaratorSyntax")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("ApiDesign", "RS0027:Public API with optional parameter(s) should have the most parameters amongst its public overloads.", Justification = "<Pending>", Scope = "member", Target = "~M:StarkPlatform.CodeAnalysis.Stark.SyntaxFactory.VariableDeclaration(StarkPlatform.CodeAnalysis.SeparatedSyntaxList{StarkPlatform.CodeAnalysis.Stark.Syntax.VariableDeclarationSyntax})~StarkPlatform.CodeAnalysis.Stark.Syntax.VariableDeclarationSyntax")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("ApiDesign", "RS0027:Public API with optional parameter(s) should have the most parameters amongst its public overloads.", Justification = "<Pending>", Scope = "member", Target = "~M:StarkPlatform.CodeAnalysis.Stark.SyntaxFactory.FieldDeclaration(StarkPlatform.CodeAnalysis.Stark.Syntax.VariableDeclarationSyntax)~StarkPlatform.CodeAnalysis.Stark.Syntax.FieldDeclarationSyntax")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("ApiDesign", "RS0027:Public API with optional parameter(s) should have the most parameters amongst its public overloads.", Justification = "<Pending>", Scope = "member", Target = "~M:StarkPlatform.CodeAnalysis.Stark.SyntaxFactory.EventFieldDeclaration(StarkPlatform.CodeAnalysis.Stark.Syntax.VariableDeclarationSyntax)~StarkPlatform.CodeAnalysis.Stark.Syntax.EventFieldDeclarationSyntax")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("ApiDesign", "RS0026:Do not add multiple public overloads with optional parameters", Justification = "<Pending>", Scope = "member", Target = "~M:StarkPlatform.CodeAnalysis.Stark.CSharpExtensions.GetDeclaredSymbol(StarkPlatform.CodeAnalysis.SemanticModel,StarkPlatform.CodeAnalysis.Stark.Syntax.DeclarationPatternSyntax,System.Threading.CancellationToken)~StarkPlatform.CodeAnalysis.ILocalSymbol")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("ApiDesign", "RS0026:Do not add multiple public overloads with optional parameters", Justification = "<Pending>", Scope = "member", Target = "~M:StarkPlatform.CodeAnalysis.Stark.CSharpExtensions.GetDeclaredSymbol(StarkPlatform.CodeAnalysis.SemanticModel,StarkPlatform.CodeAnalysis.Stark.Syntax.SingleVariableDesignationSyntax,System.Threading.CancellationToken)~StarkPlatform.CodeAnalysis.ISymbol")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("ApiDesign", "RS0026:Do not add multiple public overloads with optional parameters", Justification = "<Pending>", Scope = "member", Target = "~M:StarkPlatform.CodeAnalysis.Stark.CSharpExtensions.GetDeclaredSymbol(StarkPlatform.CodeAnalysis.SemanticModel,StarkPlatform.CodeAnalysis.Stark.Syntax.TupleElementSyntax,System.Threading.CancellationToken)~StarkPlatform.CodeAnalysis.ISymbol")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("ApiDesign", "RS0027:Public API with optional parameter(s) should have the most parameters amongst its public overloads.", Justification = "<Pending>", Scope = "member", Target = "~M:StarkPlatform.CodeAnalysis.Stark.SyntaxFactory.ParenthesizedVariableComponent(StarkPlatform.CodeAnalysis.SeparatedSyntaxList{StarkPlatform.CodeAnalysis.Stark.Syntax.VariableComponentSyntax})~StarkPlatform.CodeAnalysis.Stark.Syntax.ParenthesizedVariableComponentSyntax")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("ApiDesign", "RS0027:Public API with optional parameter(s) should have the most parameters amongst its public overloads.", Justification = "<Pending>", Scope = "member", Target = "~M:StarkPlatform.CodeAnalysis.Stark.SyntaxFactory.ParenthesizedVariableDesignation(StarkPlatform.CodeAnalysis.SeparatedSyntaxList{StarkPlatform.CodeAnalysis.Stark.Syntax.VariableDesignationSyntax})~StarkPlatform.CodeAnalysis.Stark.Syntax.ParenthesizedVariableDesignationSyntax")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("ApiDesign", "RS0026:Do not add multiple public overloads with optional parameters", Justification = "<Pending>", Scope = "member", Target = "~M:StarkPlatform.CodeAnalysis.Stark.CSharpExtensions.GetDeclaredSymbol(StarkPlatform.CodeAnalysis.SemanticModel,StarkPlatform.CodeAnalysis.Stark.Syntax.TupleExpressionSyntax,System.Threading.CancellationToken)~StarkPlatform.CodeAnalysis.INamedTypeSymbol")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("ApiDesign", "RS0026:Do not add multiple public overloads with optional parameters", Justification = "<Pending>", Scope = "member", Target = "~M:StarkPlatform.CodeAnalysis.Stark.CSharpExtensions.GetDeclaredSymbol(StarkPlatform.CodeAnalysis.SemanticModel,StarkPlatform.CodeAnalysis.Stark.Syntax.ArgumentSyntax,System.Threading.CancellationToken)~StarkPlatform.CodeAnalysis.ISymbol")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("ApiDesign", "RS0027:Public API with optional parameter(s) should have the most parameters amongst its public overloads.", Justification = "<Pending>", Scope = "member", Target = "~M:StarkPlatform.CodeAnalysis.Stark.SyntaxFactory.ArrayRankSpecifier(StarkPlatform.CodeAnalysis.SeparatedSyntaxList{StarkPlatform.CodeAnalysis.Stark.Syntax.ExpressionSyntax})~StarkPlatform.CodeAnalysis.Stark.Syntax.ArrayRankSpecifierSyntax")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("ApiDesign", "RS0027:Public API with optional parameter(s) should have the most parameters amongst its public overloads.", Justification = "<Pending>", Scope = "member", Target = "~M:StarkPlatform.CodeAnalysis.Stark.SyntaxFactory.DeconstructionPattern(StarkPlatform.CodeAnalysis.SeparatedSyntaxList{StarkPlatform.CodeAnalysis.Stark.Syntax.SubpatternSyntax})~StarkPlatform.CodeAnalysis.Stark.Syntax.DeconstructionPatternSyntax")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("ApiDesign", "RS0027:Public API with optional parameter(s) should have the most parameters amongst its public overloads.", Justification = "<Pending>", Scope = "member", Target = "~M:StarkPlatform.CodeAnalysis.Stark.SyntaxFactory.PropertyPatternClause(StarkPlatform.CodeAnalysis.SeparatedSyntaxList{StarkPlatform.CodeAnalysis.Stark.Syntax.SubpatternSyntax})~StarkPlatform.CodeAnalysis.Stark.Syntax.PropertyPatternClauseSyntax")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("ApiDesign", "RS0027:Public API with optional parameter(s) should have the most parameters amongst its public overloads.", Justification = "<Pending>", Scope = "member", Target = "~M:StarkPlatform.CodeAnalysis.Stark.SyntaxFactory.PositionalPatternClause(StarkPlatform.CodeAnalysis.SeparatedSyntaxList{StarkPlatform.CodeAnalysis.Stark.Syntax.SubpatternSyntax})~StarkPlatform.CodeAnalysis.Stark.Syntax.PositionalPatternClauseSyntax")]

