// Copyright (c) Alexandre Mutel. All rights reserved.
// This file is licensed under the BSD-Clause 2 license. 
// See the license.txt file in the project root for more information.

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Reflection.Stark.Metadata;

namespace StarkPlatform.CodeAnalysis.Stark
{
    /// <summary>
    /// Defines the argument of an opcode
    /// </summary>
    internal enum OpCodeArg
    {
        None,
        Target32,
        Target8,
        TypeToken,
        Method,
        Class,
        CallSite,
        Field,
        String,
        Token,
        ElementType,
        Constructor,

        ArgumentVar,
        LocalVar,

        UInt16,
        UInt8,
        Int32,
        UInt32,
        Int8,
        Int64,
        UInt64,
        Float32,
        Float64
    }

    /// <summary>
    /// Defines IL opcodes and their argument.
    /// </summary>
    [DebuggerDisplay("{Name} Arg: {Argument}")]
    internal sealed class ILInstruction
    {
        public ILInstruction(ILOpCode opCode, string name, OpCodeArg argument)
        {
            OpCode = opCode;
            Name = name;
            Argument = argument;
        }

        public readonly ILOpCode OpCode;

        public readonly string Name;

        public readonly OpCodeArg Argument;

        public static ILInstruction Get(string name)
        {
            if (name == null) throw new ArgumentNullException(nameof(name));
            ILInstruction inst;
            Map.TryGetValue(name, out inst);
            return inst;
        }

        private static readonly Dictionary<string, ILInstruction> Map = new ILInstruction[]
        {
            new ILInstruction(ILOpCode.Add, "add", OpCodeArg.None),
            new ILInstruction(ILOpCode.Add_ovf, "add.ovf", OpCodeArg.None),
            new ILInstruction(ILOpCode.Add_ovf_un, "add.ovf.un", OpCodeArg.None),
            new ILInstruction(ILOpCode.And, "and", OpCodeArg.None),
            new ILInstruction(ILOpCode.Arglist, "arglist", OpCodeArg.None),
            new ILInstruction(ILOpCode.Beq, "beq", OpCodeArg.Target32),
            new ILInstruction(ILOpCode.Beq_s, "beq.s", OpCodeArg.Target8),
            new ILInstruction(ILOpCode.Bge, "bge", OpCodeArg.Target32),
            new ILInstruction(ILOpCode.Bge_s, "bge.s", OpCodeArg.Target8),
            new ILInstruction(ILOpCode.Bge_un, "bge.un", OpCodeArg.Target32),
            new ILInstruction(ILOpCode.Bge_un_s, "bge.un.s", OpCodeArg.Target8),
            new ILInstruction(ILOpCode.Bgt, "bgt", OpCodeArg.Target32),
            new ILInstruction(ILOpCode.Bgt_s, "bgt.s", OpCodeArg.Target8),
            new ILInstruction(ILOpCode.Bgt_un, "bgt.un", OpCodeArg.Target32),
            new ILInstruction(ILOpCode.Bgt_un_s, "bgt.un.s", OpCodeArg.Target8),
            new ILInstruction(ILOpCode.Ble, "ble", OpCodeArg.Target32),
            new ILInstruction(ILOpCode.Ble_s, "ble.s", OpCodeArg.Target8),
            new ILInstruction(ILOpCode.Ble_un, "ble.un", OpCodeArg.Target32),
            new ILInstruction(ILOpCode.Ble_un_s, "ble.un.s", OpCodeArg.Target8),
            new ILInstruction(ILOpCode.Blt, "blt", OpCodeArg.Target32),
            new ILInstruction(ILOpCode.Blt_s, "blt.s", OpCodeArg.Target8),
            new ILInstruction(ILOpCode.Blt_un, "blt.un", OpCodeArg.Target32),
            new ILInstruction(ILOpCode.Blt_un_s, "blt.un.s", OpCodeArg.Target8),
            new ILInstruction(ILOpCode.Bne_un, "bne.un", OpCodeArg.Target32),
            new ILInstruction(ILOpCode.Bne_un_s, "bne.un.s", OpCodeArg.Target8),
            new ILInstruction(ILOpCode.Box, "box", OpCodeArg.TypeToken),
            new ILInstruction(ILOpCode.Br, "br", OpCodeArg.Target32),
            new ILInstruction(ILOpCode.Br_s, "br.s", OpCodeArg.Target8),
            new ILInstruction(ILOpCode.Break, "break", OpCodeArg.None),
            new ILInstruction(ILOpCode.Brfalse, "brfalse", OpCodeArg.Target32),
            new ILInstruction(ILOpCode.Brfalse_s, "brfalse.s", OpCodeArg.Target8),
//new ILInstruction(ILOpCode.Brinst, "brinst", OpCodeArg.Target32),
//new ILInstruction(ILOpCode.Brinst_s, "brinst.s", OpCodeArg.Target8),
//new ILInstruction(ILOpCode.Brnull, "brnull", OpCodeArg.Target32),
//new ILInstruction(ILOpCode.Brnull_s, "brnull.s", OpCodeArg.Target8),
            new ILInstruction(ILOpCode.Brtrue, "brtrue", OpCodeArg.Target32),
            new ILInstruction(ILOpCode.Brtrue_s, "brtrue.s", OpCodeArg.Target8),
//new ILInstruction(ILOpCode.Brzero, "brzero", OpCodeArg.Target32),
//new ILInstruction(ILOpCode.Brzero_s, "brzero.s", OpCodeArg.Target8),
            new ILInstruction(ILOpCode.Call, "call", OpCodeArg.Method),
            new ILInstruction(ILOpCode.Calli, "calli", OpCodeArg.CallSite),
            new ILInstruction(ILOpCode.Callvirt, "callvirt", OpCodeArg.Method),
            new ILInstruction(ILOpCode.Castclass, "castclass", OpCodeArg.Class),
            new ILInstruction(ILOpCode.Ceq, "ceq", OpCodeArg.None),
            new ILInstruction(ILOpCode.Cgt, "cgt", OpCodeArg.None),
            new ILInstruction(ILOpCode.Cgt_un, "cgt.un", OpCodeArg.None),
            new ILInstruction(ILOpCode.Ckfinite, "ckfinite", OpCodeArg.None),
            new ILInstruction(ILOpCode.Clt, "clt", OpCodeArg.None),
            new ILInstruction(ILOpCode.Clt_un, "clt.un", OpCodeArg.None),
            new ILInstruction(ILOpCode.Constrained, "constrained", OpCodeArg.TypeToken),
            new ILInstruction(ILOpCode.Conv_i, "conv.i", OpCodeArg.None),
            new ILInstruction(ILOpCode.Conv_i1, "conv.i1", OpCodeArg.None),
            new ILInstruction(ILOpCode.Conv_i2, "conv.i2", OpCodeArg.None),
            new ILInstruction(ILOpCode.Conv_i4, "conv.i4", OpCodeArg.None),
            new ILInstruction(ILOpCode.Conv_i8, "conv.i8", OpCodeArg.None),
            new ILInstruction(ILOpCode.Conv_ovf_i, "conv.ovf.i", OpCodeArg.None),
            new ILInstruction(ILOpCode.Conv_ovf_i_un, "conv.ovf.i.un", OpCodeArg.None),
            new ILInstruction(ILOpCode.Conv_ovf_i1, "conv.ovf.i1", OpCodeArg.None),
            new ILInstruction(ILOpCode.Conv_ovf_i1_un, "conv.ovf.i1.un", OpCodeArg.None),
            new ILInstruction(ILOpCode.Conv_ovf_i2, "conv.ovf.i2", OpCodeArg.None),
            new ILInstruction(ILOpCode.Conv_ovf_i2_un, "conv.ovf.i2.un", OpCodeArg.None),
            new ILInstruction(ILOpCode.Conv_ovf_i4, "conv.ovf.i4", OpCodeArg.None),
            new ILInstruction(ILOpCode.Conv_ovf_i4_un, "conv.ovf.i4.un", OpCodeArg.None),
            new ILInstruction(ILOpCode.Conv_ovf_i8, "conv.ovf.i8", OpCodeArg.None),
            new ILInstruction(ILOpCode.Conv_ovf_i8_un, "conv.ovf.i8.un", OpCodeArg.None),
            new ILInstruction(ILOpCode.Conv_ovf_u, "conv.ovf.u", OpCodeArg.None),
            new ILInstruction(ILOpCode.Conv_ovf_u_un, "conv.ovf.u.un", OpCodeArg.None),
            new ILInstruction(ILOpCode.Conv_ovf_u1, "conv.ovf.u1", OpCodeArg.None),
            new ILInstruction(ILOpCode.Conv_ovf_u1_un, "conv.ovf.u1.un", OpCodeArg.None),
            new ILInstruction(ILOpCode.Conv_ovf_u2, "conv.ovf.u2", OpCodeArg.None),
            new ILInstruction(ILOpCode.Conv_ovf_u2_un, "conv.ovf.u2.un", OpCodeArg.None),
            new ILInstruction(ILOpCode.Conv_ovf_u4, "conv.ovf.u4", OpCodeArg.None),
            new ILInstruction(ILOpCode.Conv_ovf_u4_un, "conv.ovf.u4.un", OpCodeArg.None),
            new ILInstruction(ILOpCode.Conv_ovf_u8, "conv.ovf.u8", OpCodeArg.None),
            new ILInstruction(ILOpCode.Conv_ovf_u8_un, "conv.ovf.u8.un", OpCodeArg.None),
            new ILInstruction(ILOpCode.Conv_r_un, "conv.r.un", OpCodeArg.None),
            new ILInstruction(ILOpCode.Conv_r4, "conv.r4", OpCodeArg.None),
            new ILInstruction(ILOpCode.Conv_r8, "conv.r8", OpCodeArg.None),
            new ILInstruction(ILOpCode.Conv_u, "conv.u", OpCodeArg.None),
            new ILInstruction(ILOpCode.Conv_u1, "conv.u1", OpCodeArg.None),
            new ILInstruction(ILOpCode.Conv_u2, "conv.u2", OpCodeArg.None),
            new ILInstruction(ILOpCode.Conv_u4, "conv.u4", OpCodeArg.None),
            new ILInstruction(ILOpCode.Conv_u8, "conv.u8", OpCodeArg.None),
            new ILInstruction(ILOpCode.Cpblk, "cpblk", OpCodeArg.None),
            new ILInstruction(ILOpCode.Cpobj, "cpobj", OpCodeArg.TypeToken),
            new ILInstruction(ILOpCode.Div, "div", OpCodeArg.None),
            new ILInstruction(ILOpCode.Div_un, "div.un", OpCodeArg.None),
            new ILInstruction(ILOpCode.Dup, "dup", OpCodeArg.None),
//new ILInstruction(ILOpCode.EndFault, "endfault", OpCodeArg.None),
            new ILInstruction(ILOpCode.Endfilter, "endfilter", OpCodeArg.None),
            new ILInstruction(ILOpCode.Endfinally, "endfinally", OpCodeArg.None),
            new ILInstruction(ILOpCode.Initblk, "initblk", OpCodeArg.None),
            new ILInstruction(ILOpCode.Initobj, "initobj", OpCodeArg.TypeToken),
            new ILInstruction(ILOpCode.Isinst, "isinst", OpCodeArg.Class),
            new ILInstruction(ILOpCode.Jmp, "jmp", OpCodeArg.Method),
            new ILInstruction(ILOpCode.Ldarg, "ldarg", OpCodeArg.ArgumentVar), // OpCodeArg.UInt16),
            new ILInstruction(ILOpCode.Ldarg_0, "ldarg.0", OpCodeArg.None),
            new ILInstruction(ILOpCode.Ldarg_1, "ldarg.1", OpCodeArg.None),
            new ILInstruction(ILOpCode.Ldarg_2, "ldarg.2", OpCodeArg.None),
            new ILInstruction(ILOpCode.Ldarg_3, "ldarg.3", OpCodeArg.None),
            new ILInstruction(ILOpCode.Ldarg_s, "ldarg.s", OpCodeArg.UInt8),
            new ILInstruction(ILOpCode.Ldarga, "ldarga", OpCodeArg.UInt16),
            new ILInstruction(ILOpCode.Ldarga_s, "ldarga.s", OpCodeArg.UInt8),
            new ILInstruction(ILOpCode.Ldc_i4, "ldc.i4", OpCodeArg.Int32),
            new ILInstruction(ILOpCode.Ldc_i4_0, "ldc.i4.0", OpCodeArg.None),
            new ILInstruction(ILOpCode.Ldc_i4_1, "ldc.i4.1", OpCodeArg.None),
            new ILInstruction(ILOpCode.Ldc_i4_2, "ldc.i4.2", OpCodeArg.None),
            new ILInstruction(ILOpCode.Ldc_i4_3, "ldc.i4.3", OpCodeArg.None),
            new ILInstruction(ILOpCode.Ldc_i4_4, "ldc.i4.4", OpCodeArg.None),
            new ILInstruction(ILOpCode.Ldc_i4_5, "ldc.i4.5", OpCodeArg.None),
            new ILInstruction(ILOpCode.Ldc_i4_6, "ldc.i4.6", OpCodeArg.None),
            new ILInstruction(ILOpCode.Ldc_i4_7, "ldc.i4.7", OpCodeArg.None),
            new ILInstruction(ILOpCode.Ldc_i4_8, "ldc.i4.8", OpCodeArg.None),
            new ILInstruction(ILOpCode.Ldc_i4_m1, "ldc.i4.m1", OpCodeArg.None),
            new ILInstruction(ILOpCode.Ldc_i4_s, "ldc.i4.s", OpCodeArg.Int8),
            new ILInstruction(ILOpCode.Ldc_i8, "ldc.i8", OpCodeArg.Int64),
            new ILInstruction(ILOpCode.Ldc_r4, "ldc.r4", OpCodeArg.Float32),
            new ILInstruction(ILOpCode.Ldc_r8, "ldc.r8", OpCodeArg.Float64),
            new ILInstruction(ILOpCode.Ldelem, "ldelem", OpCodeArg.TypeToken),
            new ILInstruction(ILOpCode.Ldelem_i, "ldelem.i", OpCodeArg.None),
            new ILInstruction(ILOpCode.Ldelem_i1, "ldelem.i1", OpCodeArg.None),
            new ILInstruction(ILOpCode.Ldelem_i2, "ldelem.i2", OpCodeArg.None),
            new ILInstruction(ILOpCode.Ldelem_i4, "ldelem.i4", OpCodeArg.None),
            new ILInstruction(ILOpCode.Ldelem_i8, "ldelem.i8", OpCodeArg.None),
            new ILInstruction(ILOpCode.Ldelem_r4, "ldelem.r4", OpCodeArg.None),
            new ILInstruction(ILOpCode.Ldelem_r8, "ldelem.r8", OpCodeArg.None),
            new ILInstruction(ILOpCode.Ldelem_ref, "ldelem.ref", OpCodeArg.None),
            new ILInstruction(ILOpCode.Ldelem_u1, "ldelem.u1", OpCodeArg.None),
            new ILInstruction(ILOpCode.Ldelem_u2, "ldelem.u2", OpCodeArg.None),
            new ILInstruction(ILOpCode.Ldelem_u4, "ldelem.u4", OpCodeArg.None),
//new ILInstruction(ILOpCode.Ldelem_u8, "ldelem.u8", OpCodeArg.None),
            new ILInstruction(ILOpCode.Ldelema, "ldelema", OpCodeArg.Class),
            new ILInstruction(ILOpCode.Ldfld, "ldfld", OpCodeArg.Field),
            new ILInstruction(ILOpCode.Ldflda, "ldflda", OpCodeArg.Field),
            new ILInstruction(ILOpCode.Ldftn, "ldftn", OpCodeArg.Method),
            new ILInstruction(ILOpCode.Ldind_i, "ldind.i", OpCodeArg.None),
            new ILInstruction(ILOpCode.Ldind_i1, "ldind.i1", OpCodeArg.None),
            new ILInstruction(ILOpCode.Ldind_i2, "ldind.i2", OpCodeArg.None),
            new ILInstruction(ILOpCode.Ldind_i4, "ldind.i4", OpCodeArg.None),
            new ILInstruction(ILOpCode.Ldind_i8, "ldind.i8", OpCodeArg.None),
            new ILInstruction(ILOpCode.Ldind_r4, "ldind.r4", OpCodeArg.None),
            new ILInstruction(ILOpCode.Ldind_r8, "ldind.r8", OpCodeArg.None),
            new ILInstruction(ILOpCode.Ldind_ref, "ldind.ref", OpCodeArg.None),
            new ILInstruction(ILOpCode.Ldind_u1, "ldind.u1", OpCodeArg.None),
            new ILInstruction(ILOpCode.Ldind_u2, "ldind.u2", OpCodeArg.None),
            new ILInstruction(ILOpCode.Ldind_u4, "ldind.u4", OpCodeArg.None),
//new ILInstruction(ILOpCode.Ldind_u8, "ldind.u8", OpCodeArg.None),
            new ILInstruction(ILOpCode.Ldlen, "ldlen", OpCodeArg.None),
            new ILInstruction(ILOpCode.Ldloc, "ldloc", OpCodeArg.LocalVar), // OpCodeArg.UInt16),
            new ILInstruction(ILOpCode.Ldloc_0, "ldloc.0", OpCodeArg.None),
            new ILInstruction(ILOpCode.Ldloc_1, "ldloc.1", OpCodeArg.None),
            new ILInstruction(ILOpCode.Ldloc_2, "ldloc.2", OpCodeArg.None),
            new ILInstruction(ILOpCode.Ldloc_3, "ldloc.3", OpCodeArg.None),
            new ILInstruction(ILOpCode.Ldloc_s, "ldloc.s", OpCodeArg.UInt8),
            new ILInstruction(ILOpCode.Ldloca, "ldloca", OpCodeArg.UInt16),
            new ILInstruction(ILOpCode.Ldloca_s, "ldloca.s", OpCodeArg.UInt8),
            new ILInstruction(ILOpCode.Ldnull, "ldnull", OpCodeArg.None),
            new ILInstruction(ILOpCode.Ldobj, "ldobj", OpCodeArg.TypeToken),
            new ILInstruction(ILOpCode.Ldsfld, "ldsfld", OpCodeArg.Field),
            new ILInstruction(ILOpCode.Ldsflda, "ldsflda", OpCodeArg.Field),
            new ILInstruction(ILOpCode.Ldstr, "ldstr", OpCodeArg.String),
            new ILInstruction(ILOpCode.Ldtoken, "ldtoken", OpCodeArg.Token),
            new ILInstruction(ILOpCode.Ldvirtftn, "ldvirtftn", OpCodeArg.Method),
            new ILInstruction(ILOpCode.Leave, "leave", OpCodeArg.Target32),
            new ILInstruction(ILOpCode.Leave_s, "leave.s", OpCodeArg.Target8),
            new ILInstruction(ILOpCode.Localloc, "localloc", OpCodeArg.None),
            new ILInstruction(ILOpCode.Mkrefany, "mkrefany", OpCodeArg.Class),
            new ILInstruction(ILOpCode.Mul, "mul", OpCodeArg.None),
            new ILInstruction(ILOpCode.Mul_ovf, "mul.ovf", OpCodeArg.None),
            new ILInstruction(ILOpCode.Mul_ovf_un, "mul.ovf.un", OpCodeArg.None),
            new ILInstruction(ILOpCode.Neg, "neg", OpCodeArg.None),
            new ILInstruction(ILOpCode.Newarr, "newarr", OpCodeArg.ElementType),
            new ILInstruction(ILOpCode.Newobj, "newobj", OpCodeArg.Constructor),
//new ILInstruction(ILOpCode.No_typecheck, "no.typecheck", OpCodeArg.None),
//new ILInstruction(ILOpCode.No_rangecheck, "no.rangecheck", OpCodeArg.None),
//new ILInstruction(ILOpCode.No_nullcheck, "no.nullcheck", OpCodeArg.None),
            new ILInstruction(ILOpCode.Nop, "nop", OpCodeArg.None),
            new ILInstruction(ILOpCode.Not, "not", OpCodeArg.None),
            new ILInstruction(ILOpCode.Or, "or", OpCodeArg.None),
            new ILInstruction(ILOpCode.Pop, "pop", OpCodeArg.None),
            new ILInstruction(ILOpCode.Readonly, "readonly", OpCodeArg.None),
            new ILInstruction(ILOpCode.Refanytype, "refanytype", OpCodeArg.None),
            new ILInstruction(ILOpCode.Refanyval, "refanyval", OpCodeArg.TypeToken),
            new ILInstruction(ILOpCode.Rem, "rem", OpCodeArg.None),
            new ILInstruction(ILOpCode.Rem_un, "rem.un", OpCodeArg.None),
            new ILInstruction(ILOpCode.Ret, "ret", OpCodeArg.None),
            new ILInstruction(ILOpCode.Rethrow, "rethrow", OpCodeArg.None),
            new ILInstruction(ILOpCode.Shl, "shl", OpCodeArg.None),
            new ILInstruction(ILOpCode.Shr, "shr", OpCodeArg.None),
            new ILInstruction(ILOpCode.Shr_un, "shr.un", OpCodeArg.None),
            new ILInstruction(ILOpCode.Sizeof, "sizeof", OpCodeArg.TypeToken),
            new ILInstruction(ILOpCode.Starg, "starg", OpCodeArg.ArgumentVar), // OpCodeArg.UInt16),
            new ILInstruction(ILOpCode.Starg_s, "starg.s", OpCodeArg.UInt8),
            new ILInstruction(ILOpCode.Stelem, "stelem", OpCodeArg.TypeToken),
            new ILInstruction(ILOpCode.Stelem_i, "stelem.i", OpCodeArg.None),
            new ILInstruction(ILOpCode.Stelem_i1, "stelem.i1", OpCodeArg.None),
            new ILInstruction(ILOpCode.Stelem_i2, "stelem.i2", OpCodeArg.None),
            new ILInstruction(ILOpCode.Stelem_i4, "stelem.i4", OpCodeArg.None),
            new ILInstruction(ILOpCode.Stelem_i8, "stelem.i8", OpCodeArg.None),
            new ILInstruction(ILOpCode.Stelem_r4, "stelem.r4", OpCodeArg.None),
            new ILInstruction(ILOpCode.Stelem_r8, "stelem.r8", OpCodeArg.None),
            new ILInstruction(ILOpCode.Stelem_ref, "stelem.ref", OpCodeArg.None),
            new ILInstruction(ILOpCode.Stfld, "stfld", OpCodeArg.Field),
            new ILInstruction(ILOpCode.Stind_i, "stind.i", OpCodeArg.None),
            new ILInstruction(ILOpCode.Stind_i1, "stind.i1", OpCodeArg.None),
            new ILInstruction(ILOpCode.Stind_i2, "stind.i2", OpCodeArg.None),
            new ILInstruction(ILOpCode.Stind_i4, "stind.i4", OpCodeArg.None),
            new ILInstruction(ILOpCode.Stind_i8, "stind.i8", OpCodeArg.None),
            new ILInstruction(ILOpCode.Stind_r4, "stind.r4", OpCodeArg.None),
            new ILInstruction(ILOpCode.Stind_r8, "stind.r8", OpCodeArg.None),
            new ILInstruction(ILOpCode.Stind_ref, "stind.ref", OpCodeArg.None),
            new ILInstruction(ILOpCode.Stloc, "stloc", OpCodeArg.LocalVar), // OpCodeArg.UInt16),
            new ILInstruction(ILOpCode.Stloc_0, "stloc.0", OpCodeArg.None),
            new ILInstruction(ILOpCode.Stloc_1, "stloc.1", OpCodeArg.None),
            new ILInstruction(ILOpCode.Stloc_2, "stloc.2", OpCodeArg.None),
            new ILInstruction(ILOpCode.Stloc_3, "stloc.3", OpCodeArg.None),
            new ILInstruction(ILOpCode.Stloc_s, "stloc.s", OpCodeArg.UInt8),
            new ILInstruction(ILOpCode.Stobj, "stobj", OpCodeArg.TypeToken),
            new ILInstruction(ILOpCode.Stsfld, "stsfld", OpCodeArg.Field),
            new ILInstruction(ILOpCode.Sub, "sub", OpCodeArg.None),
            new ILInstruction(ILOpCode.Sub_ovf, "sub.ovf", OpCodeArg.None),
            new ILInstruction(ILOpCode.Sub_ovf_un, "sub.ovf.un", OpCodeArg.None),
            new ILInstruction(ILOpCode.Tail, "tail", OpCodeArg.None),
            new ILInstruction(ILOpCode.Throw, "throw", OpCodeArg.None),
            new ILInstruction(ILOpCode.Unaligned, "unaligned", OpCodeArg.UInt8),
            new ILInstruction(ILOpCode.Unbox, "unbox", OpCodeArg.TypeToken),
            new ILInstruction(ILOpCode.Unbox_any, "unbox.any", OpCodeArg.TypeToken),
            new ILInstruction(ILOpCode.Volatile, "volatile", OpCodeArg.None),
            new ILInstruction(ILOpCode.Xor, "xor", OpCodeArg.None),
        }.ToDictionary(instruction => instruction.Name, instruction => instruction, StringComparer.OrdinalIgnoreCase);
    }
}
