<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>Stark</string>
    <key>scopeName</key>
    <string>source.stark</string>
    <key>fileTypes</key>
    <array>
      <string>sk</string>
    </array>
    <key>uuid</key>
    <string>582789B5-991D-49E1-8E39-54327B3DBDFF</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#comment</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#extension-declaration</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#control-keywords</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#keywords</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#builtin-types</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#vector-types</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#inline-il</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#visibility-modifiers</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#attribute-declaration</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#import-declaration</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#namespace-declaration</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#module-declaration</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#func-declaration</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#invoke-declaration</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#type-declaration</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#inherit-declarations</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#keywords</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#literals</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>builtin-types</key>
      <dict>
        <key>match</key>
        <string>\b(bool|rune|f64|f32|i64|i32|i16|i8|u64|u32|u16|u8|int|uint|object|string)\b</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.type.sk</string>
          </dict>
        </dict>
      </dict>
      <key>vector-types</key>
      <dict>
        <key>match</key>
        <string>\b(f64x2|f32x4|i64x2|i32x4|i16x8|i8x16|u64x2|u32x4|u16x8|u8x16)\b</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.type.sk</string>
          </dict>
        </dict>
      </dict>
      <key>visibility-modifiers</key>
      <dict>
        <key>name</key>
        <string>storage.modifier.sk</string>
        <key>match</key>
        <string>(?&lt;!\.)\b(abstract|async|const|extern|fixed|internal|isolated|immutable|retainable|mutable|new|override|partial|private|protected|public|readonly|transient|static|unsafe|virtual|sealed)\b</string>
      </dict>
      <key>module-declaration</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(module)\b\s*([_[:alpha:]][_[:alnum:]]*)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.module.sk</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.module.sk</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>attribute-declaration</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(@)\s*([_[:alpha:]][_[:alnum:]]*(?:\s*\.\s*[_[:alpha:]][_[:alnum:]]*)*)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>markup.underline.sk</string>
              </dict>
              <key>2</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>match</key>
                    <string>[_[:alpha:]][_[:alnum:]]*</string>
                    <key>name</key>
                    <string>entity.name.type.attribute.sk</string>
                  </dict>
                </array>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>inline-il</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(unsafe)\s+(il)\b</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.unsafe.sk</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.other.il.sk</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>import-declaration</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(import)\b\s*([_[:alpha:]][_[:alnum:]]*(?:\s*\.\s*[_[:alpha:]][_[:alnum:]]*)*)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.import.sk</string>
              </dict>
              <key>2</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>match</key>
                    <string>[_[:alpha:]][_[:alnum:]]*</string>
                    <key>name</key>
                    <string>entity.name.type.import.sk</string>
                  </dict>
                </array>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(import)\b</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.import.sk</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>namespace-declaration</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(namespace)\b\s*([_[:alpha:]][_[:alnum:]]*(?:\s*\.\s*[_[:alpha:]][_[:alnum:]]*)*)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.namespace.sk</string>
              </dict>
              <key>2</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>match</key>
                    <string>[_[:alpha:]][_[:alnum:]]*</string>
                    <key>name</key>
                    <string>entity.name.type.namespace.sk</string>
                  </dict>
                </array>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(namespace)\b</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.namespace.sk</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>type-declaration</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(class)\b\s*([_[:alpha:]][_[:alnum:]]*)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.class.sk</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.class.sk</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(struct)\b\s*([_[:alpha:]][_[:alnum:]]*)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.struct.sk</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.struct.sk</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(interface)\b\s*([_[:alpha:]][_[:alnum:]]*)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.interface.sk</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.interface.sk</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(enum)\b\s*([_[:alpha:]][_[:alnum:]]*)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.enum.sk</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.enum.sk</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.other.union.sk</string>
            <key>match</key>
            <string>\b(union)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.other.struct.sk</string>
            <key>match</key>
            <string>\b(struct)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.other.class.sk</string>
            <key>match</key>
            <string>\b(class)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.other.interface.sk</string>
            <key>match</key>
            <string>\b(interface)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.other.enum.sk</string>
            <key>match</key>
            <string>\b(enum)\b</string>
          </dict>
        </array>
      </dict>
      <key>extension-declaration</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(extension)\b\s*([_[:alpha:]][_[:alnum:]]*)\s*(?:&lt;[^&gt;]*&gt;)?\s*\b(for)\b\s*([_[:alpha:]][_[:alnum:]]*)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.extension.sk</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.extension.sk</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>keyword.other.for.sk</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.class.sk</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(extension)\b</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.extension.sk</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>inherit-declarations</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(extends)\b\s*([_[:alpha:]][_[:alnum:]]*)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.extends.sk</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.class.sk</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(implements)\b\s*([_[:alpha:]][_[:alnum:]]*)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.implements.sk</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.interface.sk</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.other.extends.sk</string>
            <key>match</key>
            <string>\b(extends)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.other.implements.sk</string>
            <key>match</key>
            <string>\b(implements)\b</string>
          </dict>
        </array>
      </dict>
      <key>func-declaration</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(func)\b\s*(operator)\b</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.func.sk</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.other.operator.sk</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(func)\b\s*([_[:alpha:]][_[:alnum:]]*)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.func.sk</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.cs</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.other.func.sk</string>
            <key>match</key>
            <string>\bfunc\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.other.constructor.sk</string>
            <key>match</key>
            <string>\bconstructor\b</string>
          </dict>
        </array>
      </dict>
      <key>invoke-declaration</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>([_[:alpha:]][_[:alnum:]]*)(?:\s*\()</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.cs</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>control-keywords</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>keyword.control.conditional.if.sk</string>
            <key>match</key>
            <string>\bif\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.control.conditional.then.sk</string>
            <key>match</key>
            <string>\bthen\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.control.conditional.else.sk</string>
            <key>match</key>
            <string>\belse\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.control.loop.do.sk</string>
            <key>match</key>
            <string>\bdo\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.control.loop.while.sk</string>
            <key>match</key>
            <string>\bwhile\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.control.loop.for.sk</string>
            <key>match</key>
            <string>\bfor\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.control.try.sk</string>
            <key>match</key>
            <string>\btry\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.control.catch.sk</string>
            <key>match</key>
            <string>\bcatch\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.control.flow.yield.sk</string>
            <key>match</key>
            <string>\byield\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.control.flow.return.sk</string>
            <key>match</key>
            <string>\breturn\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.control.flow.break.sk</string>
            <key>match</key>
            <string>\bbreak\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.control.flow.continue.sk</string>
            <key>match</key>
            <string>\bcontinue\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.control.flow.throw.sk</string>
            <key>match</key>
            <string>\bthrow\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.control.flow.switch.sk</string>
            <key>match</key>
            <string>\bswitch\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.control.flow.case.sk</string>
            <key>match</key>
            <string>\bcase\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.control.flow.with.sk</string>
            <key>match</key>
            <string>\bwith\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>constant.language.boolean.true.sk</string>
            <key>match</key>
            <string>\btrue\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>constant.language.boolean.false.sk</string>
            <key>match</key>
            <string>\bfalse\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>constant.language.class.null.sk</string>
            <key>match</key>
            <string>\bnull\b</string>
          </dict>
        </array>
      </dict>
      <key>keywords</key>
      <dict>
        <key>name</key>
        <string>keyword.type.sk</string>
        <key>match</key>
        <string>\b(alias|as|await|base|default|fatal|get|is|has|let|match|operator|out|params|ref|in|requires|set|sizeof|this|throws|typeof|value|var|where)\b</string>
      </dict>
      <key>comment</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>comment.block.sk</string>
            <key>begin</key>
            <string>/\*</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.sk</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\*/</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.sk</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>begin</key>
            <string>(^\s+)?(?=//)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.whitespace.comment.leading.sk</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=$)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>name</key>
                <string>comment.block.documentation.sk</string>
                <key>begin</key>
                <string>(?&lt;!/)///(?!/)</string>
                <key>beginCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.comment.sk</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>(?=$)</string>
              </dict>
              <dict>
                <key>name</key>
                <string>comment.line.double-slash.sk</string>
                <key>begin</key>
                <string>(?&lt;!/)//(?!/)</string>
                <key>beginCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.definition.comment.sk</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>(?=$)</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>literals</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#numeric-literal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#char-literal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#string-literal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#verbatim-string-literal</string>
          </dict>
        </array>
      </dict>
      <key>numeric-literal</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.numeric.hex.sk</string>
            <key>match</key>
            <string>\b0(x|X)[0-9a-fA-F_]+(i8|i16|i32|i64|u8|u16|u32|u64)?\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>constant.numeric.binary.sk</string>
            <key>match</key>
            <string>\b0(b|B)[01_]+(i8|i16|i32|i64|u8|u16|u32|u64)?\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>constant.numeric.decimal.sk</string>
            <key>match</key>
            <string>\b([0-9_]+)?\.[0-9_]+((e|E)[0-9]+)?(f32|64)?\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>constant.numeric.decimal.sk</string>
            <key>match</key>
            <string>\b[0-9_]+(e|E)[0-9_]+(f32|f64)?\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>constant.numeric.decimal.sk</string>
            <key>match</key>
            <string>\b[0-9_]+(f32|f64)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>constant.numeric.decimal.sk</string>
            <key>match</key>
            <string>\b[0-9_]+(i8|i16|i32|i64|u8|u16|u32|u64)?\b</string>
          </dict>
        </array>
      </dict>
      <key>char-literal</key>
      <dict>
        <key>name</key>
        <string>string.quoted.single.sk</string>
        <key>begin</key>
        <string>'</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.char.begin.sk</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(\')|((?:[^\\\n])$)</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.char.end.sk</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>invalid.illegal.newline.sk</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#string-character-escape</string>
          </dict>
        </array>
      </dict>
      <key>string-character-escape</key>
      <dict>
        <key>name</key>
        <string>constant.character.escape.sk</string>
        <key>match</key>
        <string>\\.</string>
      </dict>
      <key>string-literal</key>
      <dict>
        <key>name</key>
        <string>string.quoted.double.sk</string>
        <key>begin</key>
        <string>(?&lt;!@)"</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.sk</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(")|((?:[^\\\n])$)</string>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.sk</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>invalid.illegal.newline.sk</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#string-character-escape</string>
          </dict>
        </array>
      </dict>
      <key>verbatim-string-character-escape</key>
      <dict>
        <key>name</key>
        <string>constant.character.escape.sk</string>
        <key>match</key>
        <string>""</string>
      </dict>
      <key>verbatim-string-literal</key>
      <dict>
        <key>name</key>
        <string>string.quoted.double.sk</string>
        <key>begin</key>
        <string>`"</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.sk</string>
          </dict>
        </dict>
        <key>end</key>
        <string>"`</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.sk</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#verbatim-string-character-escape</string>
          </dict>
        </array>
      </dict>
    </dict>
  </dict>
</plist>